"""Three offline, self-contained grayscale backtest debugging pages."""
from __future__ import annotations
import base64,gzip,json
from pathlib import Path
import pandas as pd
OUT=Path(__file__).resolve().parent
TITLES={'continuation':('波动尺度与动量保留','盘前振幅相对历史是否异常？夜盘与盘前的动量是否保留，开盘后还剩多少空间？'),
        'repair':('下跌后的修复','同样的盘前涨幅，曾经探底再恢复和一路上涨，后续空间是否不同？'),
        'relative':('相对市场定价','比QQQ更强时，开盘后剩余空间是否更多？观察个股同窗超额、广度和分化。')}

TEMPLATE=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__ · 盘前研究调试</title>
<style>
:root{--bg:#fff;--fg:#171717;--muted:#666;--line:#b7b7b7;--panel:#f4f4f4;--shade:#e6e6e6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 system-ui,sans-serif;font-variant-numeric:tabular-nums}main{max-width:1480px;margin:auto;padding:22px}h1{font-size:25px;margin:6px 0}h2{font-size:17px;margin:0 0 10px}p{margin:7px 0;color:var(--muted)}a{color:inherit;text-underline-offset:3px}nav{display:flex;gap:18px;flex-wrap:wrap;padding-bottom:12px;border-bottom:1px solid var(--line)}section,aside{border:1px solid var(--line);padding:15px;min-width:0}header{padding:16px 0}.tag{display:inline-block;border:1px solid var(--line);padding:2px 7px;font-size:12px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:12px}.stack{display:grid;gap:12px;min-width:0}.form{display:flex;flex-wrap:wrap;align-items:end;gap:10px}label{display:grid;gap:4px;font-size:12px}input,select,button{font:inherit;background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:7px;min-height:36px;min-width:0;max-width:100%;border-radius:0}button,a,select{cursor:pointer}button:hover{background:var(--shade)}:focus-visible{outline:2px solid var(--fg);outline-offset:3px}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.metric{border-top:2px solid var(--line);padding-top:8px}.metric strong{display:block;font-size:24px}.metric small{display:block;color:var(--muted)}canvas{display:block;width:100%;max-width:100%;touch-action:pan-y}#mini{height:112px;cursor:crosshair}#chart{height:370px}.scroll{overflow-x:auto;max-width:100%}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:7px 8px;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}th:first-child,td:first-child{text-align:left}tbody tr:hover{background:var(--panel)}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:12px}.swatch{border:1px solid var(--line);padding:2px 8px}.muted{color:var(--muted)}.note{border-left:2px solid var(--fg);padding-left:9px;font-size:12px}.range-controls{display:grid;grid-template-columns:1fr 1fr;gap:14px}.range-controls input{width:100%;padding:0}details{border-top:1px solid var(--line);padding-top:8px;margin-top:10px}summary{cursor:pointer}.compact{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}#hover{min-height:52px;font-size:12px}#loading{padding:40px}button.stock{padding:2px 6px;min-height:27px}footer{font-size:12px;border-top:1px solid var(--line);margin-top:15px;padding-top:12px}.empty{padding:20px;text-align:center;color:var(--muted)}@media(max-width:850px){main{padding:12px}.layout{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}h1{font-size:21px}#chart{height:310px}.form label{flex:1 1 130px;min-width:0}.form button{flex:0 0 auto}}@media(prefers-color-scheme:dark){:root{--bg:#171717;--fg:#eee;--muted:#aaa;--line:#626262;--panel:#232323;--shade:#393939}}
</style>
<main><nav aria-label="研究路线"><a href="index.html">研究总览</a><a href="continuation.html">01 波动与动量</a><a href="repair.html">02 下跌修复</a><a href="relative.html">03 相对异动</a></nav><header><span class="tag">WIREFRAME / 历史前向回测 v2</span><h1>__TITLE__</h1><p>__QUESTION__</p><div id="frozen" class="note">正在读取真实回测…</div></header><div id="loading">加载此页面内嵌的行情和冻结预测，无网络请求…</div>
<div id="app" hidden><div class="layout"><div class="stack"><section><h2>观察范围</h2><div class="form"><label>模型版本<select id="version"><option value="monthly" selected>按月更新 v2.1</option><option value="fixed">固定年度 v2</option></select></label><label>股票池<select id="pool"><option value="favorites">特别关注</option><option value="watch">futud 全部自选</option><option value="qqq">QQQ及其成分</option><option value="etf">ETF 成分（已获取）</option><option value="all">全部已登记</option></select></label><label>股票<select id="symbol"></select></label><label>起点（ET）<input type="date" id="start" min="2024-10-03" max="2026-10-02"></label><label>终点（ET）<input type="date" id="end" min="2024-10-03" max="2026-10-02"></label></div><div class="form" style="margin-top:10px"><button data-days="30">30 天</button><button data-days="60">60 天</button><button data-days="90">90 天</button><button data-days="180">180 天</button><button id="twoYears">两年全范围</button><button id="frozenPeriod">冻结评分区间</button><label>主图粒度<select id="grain"><option value="hourly">小时（由真实5m聚合）</option><option value="daily">日级常规盘</option></select></label></div><p class="compact">快捷项为日历天。时区 America/New_York；两年请求范围 2024-10-03—2026-10-02。缺失保留空白。</p></section>
<section><h2>两年 mini 导航 · 日级 K 线</h2><canvas id="mini" tabindex="0" role="img" aria-label="两年日级K线，点击选择区间，左右方向键平移"></canvas><div class="range-controls"><label>区间起点<input id="miniStart" type="range" min="0" max="729" aria-label="mini区间起点"></label><label>区间终点<input id="miniEnd" type="range" min="0" max="729" aria-label="mini区间终点"></label></div><p id="coverage"></p></section>
<section><div class="form" style="justify-content:space-between"><h2 id="chartTitle">全日行情</h2><span class="tag">滚轮 / 拖拽 / 触控缩放均关闭</span></div><div class="legend"><span class="swatch" style="background:var(--bg)">常规盘</span><span class="swatch" style="background:var(--panel)">盘前</span><span class="swatch" style="background:var(--shade)">盘后</span><span class="swatch">斜线：夜盘</span><span class="swatch">密斜线：非交易日</span></div><canvas id="chart" role="img" aria-label="全日K线与时段标记"></canvas><div id="hover" class="compact">悬停读取 OHLC / 时段 / 冻结信号。K线不会响应鼠标缩放。</div><p id="signalNote" class="note"></p></section>
<section><h2>当前区间回测 · <span id="mode">冻结配置</span></h2><div class="form"><label>+3%预测的选择阈值<input type="number" id="threshold" min="0" max="1" step="0.01"></label><label>评价已有信号的目标<select id="target"><option value="0.01">当天触及 +1%</option><option value="0.02">当天触及 +2%</option><option value="0.03" selected>当天触及 +3%</option><option value="0.05">当天触及 +5%</option><option value="close">当天收盘上涨</option></select></label><label>价格参考<select id="entry"><option value="open">09:30 Open</option><option value="delay">09:35 Open（延迟敏感性）</option></select></label><label>信号日期<select id="period"><option value="test">只评估冻结外层</option><option value="all">含校准期（仅探索）</option></select></label><button id="reset">恢复冻结配置</button><button id="export">导出当前明细 CSV</button></div><p>其它目标只评价同一批 +3% 模型信号，未重新训练相应概率。改变配置或日期不会改写冻结通过结论。</p><div id="metrics" class="metrics"></div><div class="scroll"><table><thead><tr><th>股票 · 点击下钻</th><th>信号/机会</th><th>TP/FP</th><th>Precision</th><th>Wilson 95%</th><th>同股基准</th><th>增量</th><th>召回</th><th>月数</th><th>登记/验收</th></tr></thead><tbody id="stockRows"></tbody></table></div></section>
<section><h2>当前日预测与输入</h2><p id="dayProvenance"></p><div id="dayForecast" class="note"></div><details><summary>查看当日所有模型输入（09:25已知）</summary><div id="dayFeatures" class="compact"></div></details></section><section><h2>逐日信号与失败复盘</h2><div class="scroll"><table><thead><tr><th>日期 ET</th><th>+3%概率</th><th>选择</th><th>实际触及</th><th>预测MFE 中位 [20/80]</th><th>MFE</th><th>MAE</th><th>收盘</th><th>夜盘涨跌</th><th>盘前涨跌</th><th>特征截止</th></tr></thead><tbody id="events"></tbody></table></div><p>最多显示最近80行；CSV包含当前股票全部筛选行。图中 ○ 为命中、× 为失败，只标外层信号。</p></section></div>
<aside><h2>证据与规则</h2><p class="note">09:25 截止输入 → 09:25:30 决策 → 09:30 Open 仅作标签价格。当天未来高低价只能用于结果。</p><p id="split"></p><div id="evidence"></div><details open><summary>此路线的可检验机制</summary><p>__QUESTION__</p><div id="features" class="compact"></div><p class="compact">盘前跳空=09:25 Close/昨常规Close−1；盘前振幅=(High−Low)/昨常规Close；归一化尺度=此前20完整常规日均振幅。相对值=个股−QQQ同窗值；回弹=盘前末Close/盘前Low−1；路径效率=|净log涨跌|/Σ|逐柱log涨跌|。历史基准只用此前已成熟日。</p></details><details><summary>股票池与行情缺口</summary><div id="scope" class="compact"></div></details><details><summary>冻结外层逐月结果</summary><div class="scroll"><table><thead><tr><th>月份</th><th>n</th><th>命中</th><th>增量</th></tr></thead><tbody id="months"></tbody></table></div></details><details><summary>概率校准</summary><div id="reliability" class="compact"></div></details><details><summary>费用与执行边界</summary><p>另存 +3% / −1% 先达代理：同一5m同时触及按止损，双边成本共0.2%；未触及按收盘。未模拟盘口、真实订单、资金限制，不能把日内 High 当成交卖价。日线只展示常规盘；全日观察请选小时。</p></details><details><summary>复算与来源</summary><p><a href="PROTOCOL.md">运行前协议</a> · <a href="REPORT.md">研究结果</a> · <a href="audit.json">数据审计</a> · <a href="universe.json">股票池快照</a></p><p>全部代码及数据快照均在本目录。历史到达时间为 end+1秒假设；当前池回溯、已暴露历史，独立前向验证尚未完成。</p></details></aside></div><footer>布局采用“证据与图形联动调试台”：同一日期选择同时控制K线与统计，冻结证据独立保留。视觉品牌、动画与交易入口留待后续产品设计；本页面只读。</footer></div></main>
<script id="payload" type="application/octet-stream">__PAYLOAD__</script><script>
const ROUTE='__ROUTE__';let D,BUNDLE,symbol,chartBars=[],filtered=[],canvasMap;const $=id=>document.getElementById(id);const pct=v=>v==null?'—':(v*100).toFixed(1)+'%';const num=v=>v==null?'—':Number(v).toFixed(2);const minDate='2024-10-03',maxDate='2026-10-02',T0=Date.parse(minDate+'T00:00:00Z'),T1=Date.parse('2026-10-03T00:00:00Z'),DAY=86400000;const stamp=s=>Date.parse(s+'Z');const date=v=>new Date(v).toISOString().slice(0,10);const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function poolMembers(){return Object.values(D.universe.members).filter(m=>$('pool').value==='all'||($('pool').value==='favorites'&&m.groups.includes('特别关注'))||($('pool').value==='watch'&&m.groups.includes('futud自选'))||($('pool').value==='qqq'&&m.groups.some(g=>g.startsWith('QQQ'))) ||($('pool').value==='etf'&&m.groups.some(g=>g.startsWith('ETF成分'))));}
function chooseStock(keep){const list=poolMembers().sort((a,b)=>(!!D.charts[b.symbol]-!!D.charts[a.symbol])||a.symbol.localeCompare(b.symbol));$('symbol').innerHTML=list.map(m=>`<option value="${esc(m.symbol)}">${esc(m.symbol)} · ${esc(m.name)}${D.charts[m.symbol]?'':' [缺行情]'}</option>`).join('');const selected=list.find(m=>m.symbol===keep)||list.find(m=>m.symbol==='CRDO')||list[0];symbol=selected?.symbol;if(symbol)$('symbol').value=symbol;render();}
function canvas(id){let c=$(id),box=c.getBoundingClientRect(),w=Math.max(200,box.width),h=box.height,ratio=window.devicePixelRatio||1;c.width=w*ratio;c.height=h*ratio;let x=c.getContext('2d');x.scale(ratio,ratio);return {c,x,w,h};}
function colors(){let s=getComputedStyle(document.documentElement);return ['--bg','--fg','--muted','--line','--panel','--shade'].map(k=>s.getPropertyValue(k).trim());}
function candle(x,b,px,py,scale,width,fg,bg){const [o,h,l,c]=b;x.strokeStyle=fg;x.lineWidth=.8;x.beginPath();x.moveTo(px,py(h));x.lineTo(px,py(l));x.stroke();x.fillStyle=c>=o?fg:bg;let top=py(Math.max(o,c)),height=Math.max(1,Math.abs(py(c)-py(o)));x.fillRect(px-width/2,top,width,height);x.strokeRect(px-width/2,top,width,height);}
function mini(){const {x,w,h}=canvas('mini'),[bg,fg,mut,line,panel,shade]=colors();x.fillStyle=bg;x.fillRect(0,0,w,h);const bars=D.charts[symbol]?.daily||[],valid=bars.filter(b=>b[0]>=minDate);let lo=Math.min(...valid.map(b=>b[3])),hi=Math.max(...valid.map(b=>b[2]));if(!valid.length){lo=0;hi=1;}let py=p=>h-20-(p-lo)/Math.max(hi-lo,1e-9)*(h-32),px=t=>(t-T0)/(T1-T0)*w;const starts=[T0,Date.parse('2025-10-01Z'),Date.parse('2026-01-01Z'),T1];x.fillStyle=panel;x.fillRect(px(starts[1]),0,px(starts[2])-px(starts[1]),h);x.fillStyle=shade;let a=stamp($('start').value+'T00:00'),b=stamp($('end').value+'T23:59');x.fillRect(px(a),0,px(b)-px(a),h);for(let r of valid)candle(x,r.slice(1,5),px(stamp(r[0]+'T12:00')),py,1,Math.max(.6,w/730*.6),fg,bg);x.fillStyle=mut;x.font='10px system-ui';x.fillText('2024-10 · 训练',3,h-4);x.fillText('2025-10 · 校准',px(starts[1])+4,h-4);x.fillText('2026 · 外层',px(starts[2])+4,h-4);x.strokeStyle=fg;x.strokeRect(px(a),1,px(b)-px(a),h-18);$('miniStart').max=$('miniEnd').max=Math.floor((T1-T0)/DAY)-1;$('miniStart').value=Math.round((a-T0)/DAY);$('miniEnd').value=Math.round((stamp($('end').value+'T00:00')-T0)/DAY);}
function hatch(x,left,right,top,bottom,step,color){x.save();x.beginPath();x.rect(left,top,right-left,bottom-top);x.clip();x.strokeStyle=color;x.lineWidth=.5;for(let p=left-bottom;p<right;p+=step){x.beginPath();x.moveTo(p,bottom);x.lineTo(p+bottom-top,top);x.stroke();}x.restore();}
function chart(){$('hover').textContent='悬停读取 OHLC / 时段 / 冻结信号。K线不会响应鼠标缩放。';const {x,w,h}=canvas('chart'),[bg,fg,mut,line,panel,shade]=colors(),left=48,right=w-10,top=30,bottom=h-27;let from=stamp($('start').value+'T00:00'),to=stamp($('end').value+'T00:00')+DAY;let px=t=>left+(t-from)/(to-from)*(right-left);x.fillStyle=bg;x.fillRect(0,0,w,h);for(let d=from;d<to;d+=DAY){const ds=date(d),session=D.sessions[ds];if(!session){x.fillStyle=panel;x.fillRect(px(d),top,px(d+DAY)-px(d),bottom-top);hatch(x,px(d),px(d+DAY),top,bottom,7,line);}else if($('grain').value==='hourly'){const close=570+session;for(let [a,b,fill] of [[240,570,panel],[close,1200,shade]]){x.fillStyle=fill;x.fillRect(px(d+a*60000),top,px(d+b*60000)-px(d+a*60000),bottom-top);}for(let [a,b] of [[0,240],[1200,1440]])hatch(x,px(d+a*60000),px(d+b*60000),top,bottom,14,line);}if(to-from<=14*DAY){x.fillStyle=mut;x.font='10px system-ui';x.fillText(ds.slice(5),px(d)+2,h-5);}}
const raw=D.charts[symbol]?.[$('grain').value]||[];chartBars=raw.filter(b=>b[0].slice(0,10)>=$('start').value&&b[0].slice(0,10)<=$('end').value);if(!chartBars.length){x.fillStyle=mut;x.fillText('此股票 / 区间缺少真实行情',left+15,60);canvasMap=null;return;}
const daily=$('grain').value==='daily';let hi=Math.max(...chartBars.map(b=>b[daily?2:3])),lo=Math.min(...chartBars.map(b=>b[daily?3:4]));let spread=Math.max(hi-lo,.01);hi+=spread*.08;lo-=spread*.08;let py=p=>bottom-(p-lo)/(hi-lo)*(bottom-top);x.font='10px system-ui';for(let i=0;i<5;i++){let p=lo+(hi-lo)*i/4;x.strokeStyle=line;x.beginPath();x.moveTo(left,py(p));x.lineTo(right,py(p));x.stroke();x.fillStyle=mut;x.fillText(p.toFixed(1),2,py(p)+4);}let barWidth=Math.max(.5,Math.min(8,(right-left)/(to-from)* (daily?DAY:3600000)*.6));for(let b of chartBars){let t=stamp(daily?b[0]+'T12:00':b[0]);if(!daily&&b[8]<(stamp(b[1])-stamp(b[0]))/300000)x.setLineDash([2,2]);candle(x,b.slice(daily?1:2,daily?5:6),px(t),py,1,barWidth,fg,bg);x.setLineDash([]);}
const score='score_'+ROUTE,threshold=+$('threshold').value;let signals=D.predictions.filter(r=>r.symbol===symbol&&r.period==='test'&&r.day>=$('start').value&&r.day<=$('end').value&&r[score]>=threshold);x.fillStyle=fg;x.font='13px system-ui';for(let r of signals){let t=stamp(r.day+'T09:30');x.fillText(hit(r)?'○':'×',px(t)-4,py(r.reference)-7);if(to-from<=3*DAY){x.strokeStyle=fg;x.setLineDash([3,3]);x.beginPath();x.moveTo(px(stamp(r.day+'T09:25')),top);x.lineTo(px(stamp(r.day+'T09:25')),bottom);x.stroke();x.setLineDash([]);}}
x.fillStyle=mut;x.font='11px system-ui';x.fillText($('start').value,left,16);x.fillText($('end').value,Math.max(left,right-85),16);canvasMap={from,to,left,right,px,py};$('chartTitle').textContent=symbol+' · '+(daily?'日级常规盘':'全日小时聚合');}
function hit(r){let t=$('target').value,delay=$('entry').value==='delay';return t==='close'?(delay?r.delayed_close_ret:r.close_ret)>0:(delay?r.delayed_mfe:r.mfe)>=+t;}
function summary(rows){let selected=rows.filter(r=>r['score_'+ROUTE]>=+$('threshold').value),k=selected.filter(hit).length,total=rows.filter(hit).length,n=selected.length,b=rows.length?total/rows.length:null,p=n?k/n:null;let z=1.959964,center=n?(p+z*z/(2*n))/(1+z*z/n):null,delta=n?z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/(1+z*z/n):null;return {rows,selected,n,k,p,b,lift:p==null?null:p-b,recall:total?k/total:null,ci:n?[center-delta,center+delta]:[null,null],months:new Set(selected.map(r=>r.day.slice(0,7))).size};}
function render(){if(!D||!symbol)return;let config=D.results.routes[ROUTE],a=$('start').value,b=$('end').value;if(!a||!b||a>b){$('signalNote').textContent='起点必须不晚于终点。';return;}
const members=poolMembers(),set=new Set(members.map(m=>m.symbol));filtered=D.predictions.filter(r=>set.has(r.symbol)&&r.day>=a&&r.day<=b&&($('period').value==='all'||r.period==='test'));let group=summary(filtered),selected=summary(filtered.filter(r=>r.symbol===symbol));const baseBy={};for(const r of filtered){let a=baseBy[r.symbol]??=[0,0];a[0]+=+hit(r);a[1]++;}let matched=group.n?group.selected.reduce((sum,r)=>sum+baseBy[r.symbol][0]/baseBy[r.symbol][1],0)/group.n:null;
$('metrics').innerHTML=[['池内命中率',pct(group.p),group.k+' TP / '+(group.n-group.k)+' FP'],['同股匹配基准',pct(matched),'增量 '+pct(group.p==null?null:group.p-matched)],['信号供给',group.n,group.rows.length+' 个可评分股票日'],[symbol+' 命中率',pct(selected.p),selected.n+' 信号 / '+selected.months+' 月']].map(([a,b,c])=>`<div class="metric"><small>${a}</small><strong>${b}</strong><small>${c}</small></div>`).join('');
const frozenStatus=+$('threshold').value===config.threshold&&$('target').value==='0.03'&&$('entry').value==='open'&&$('period').value==='test';$('mode').textContent=frozenStatus?'冻结模型 · 当前日期子集（非完整验收）':'探索配置 · 不具有通过状态';
$('stockRows').innerHTML=members.map(m=>{let rows=filtered.filter(r=>r.symbol===m.symbol),s=summary(rows),f=config.symbols.find(x=>x.symbol===m.symbol);return `<tr><td><button class="stock" data-stock="${esc(m.symbol)}">${esc(m.symbol)}</button></td><td>${s.n}/${rows.length}</td><td>${s.k}/${s.n-s.k}</td><td>${pct(s.p)}</td><td>${pct(s.ci[0])}–${pct(s.ci[1])}</td><td>${pct(s.b)}</td><td>${pct(s.lift)}</td><td>${pct(s.recall)}</td><td>${s.months}</td><td>${f?.enrolled_in_calibration?'校准期登记':'未登记'} / ${f?.pass?'冻结个股达标':'未通过'}</td></tr>`;}).join('');
let events=filtered.filter(r=>r.symbol===symbol).sort((a,b)=>b.day.localeCompare(a.day));$('events').innerHTML=events.slice(0,80).map(r=>`<tr><td><button class="stock" data-day="${r.day}">${r.day}</button></td><td>${pct(r['score_'+ROUTE])}</td><td>${r['score_'+ROUTE]>=+$('threshold').value?'信号':'—'}</td><td>${hit(r)?'触及':'未触及'}</td><td>${pct(r["mfe_"+ROUTE+"_50"])} [${pct(r["mfe_"+ROUTE+"_20"])} / ${pct(r["mfe_"+ROUTE+"_80"])}]</td><td>${pct(r.mfe)}</td><td>${pct(r.mae)}</td><td>${pct(r.close_ret)}</td><td>${pct(r.night_ret)}</td><td>${pct(r.pre_ret)}</td><td>${r.feature_end.slice(11)}</td></tr>`).join('')||'<tr><td colspan="11">此区间没有可评分行；训练期不伪造样本外预测。</td></tr>';
const detail=events[0];$('dayProvenance').textContent=detail?`${detail.day} · 当前股票区间内最新可评分日。模型 ${detail.fold||'固定年度'}；训练结束 ${detail.train_end||'2025-09-30'}；校准结束 ${detail.calibration_end||'2025-12-31'}。`:'此区间没有冻结预测。';$('dayForecast').textContent=detail?`校准+3%概率 ${pct(detail['score_'+ROUTE])}；MFE中位预测 ${pct(detail['mfe_'+ROUTE+'_50'])}，20/80分位 ${pct(detail['mfe_'+ROUTE+'_20'])} / ${pct(detail['mfe_'+ROUTE+'_80'])}。实际MFE ${pct(detail.mfe)}，MAE ${pct(detail.mae)}。盘前最后正成交距截止 ${num(detail.pre_trade_age_minutes)}分钟；夜盘实际观测跨度 ${num(detail.night_span_minutes)}分钟。`:'—';$('dayFeatures').innerHTML=detail?config.features.map(k=>`<p>${esc(k)}: ${detail[k]==null?'缺失':Number(detail[k]).toFixed(6)}</p>`).join(''):'';
$('signalNote').textContent='输入截止09:25；小时聚合可能跨过截止，不能整根当输入；虚线柱包含缺失5m，只聚合实际柱。当天最高价触及为事后标签，'+(events.length?'点日期可查看单日路径。':'缺失和训练期无信号保留原样。');const c=D.audit.coverage.find(x=>x.symbol===symbol);$('coverage').textContent=c?`实际原始范围 ${c.first_raw||'无'}—${c.last_raw||'无'}；完整常规日 ${c.complete_rth||0}；夜盘+盘前合格日 ${c.eligible}。`:'未取得行情';mini();chart();}
function showEvidence(){const r=D.results.routes[ROUTE];$('frozen').innerHTML=`完整冻结外层（全池）：<b>${r.pass?'历史增量门槛通过':'历史增量门槛未通过'}</b>；${r.summary.n}信号，precision ${pct(r.summary.precision)}；特别关注股票 ${pct(r.favorite_summary?.precision)} / ${r.favorite_summary?.n||0}信号，同股增量 ${pct(r.summary.lift)}；特别关注股票达标 ${r.favorite_passed.length}/5。数据全池完整验收${D.audit.incomplete_etf_scope?'未通过':'见审计'}。`;
$('features').textContent=r.features.join(' · ');$('evidence').innerHTML=`<p>MFE中位平均绝对误差 ${pct(r.amplitude.mae_median)}<br>20/80预测区间实际覆盖 ${pct(r.amplitude.q20_q80_coverage)}（名义60%）<br>分位交叉 ${r.amplitude.quantile_crossing}<br>冻结阈值 ${r.threshold}<br>校准门槛 ${r.calibration_gate?'通过':'失败'}<br>同股内 AUC ${num(r.within_stock_auc)}<br>Brier ${num(r.brier)}<br>H基准 Brier ${num(r.h_brier)}<br>Brier改善区间 ${r.brier_improvement.ci.map(v=>v==null?'—':v.toFixed(4)).join('—')}<br>同股增量95%区间 ${r.lift_block.ci.map(pct).join('—')}<br>Holm p ${num(r.holm_p)}</p>`;
$('months').innerHTML=r.months.map(m=>`<tr><td>${m.month}</td><td>${m.n}</td><td>${pct(m.precision)}</td><td>${pct(m.lift)}</td></tr>`).join('');$('reliability').innerHTML=r.reliability.map(b=>`<p>${pct(b.lo)}—${pct(b.hi)}：n=${b.n}，预测 ${pct(b.prediction)} / 实际 ${pct(b.observed)}</p>`).join('');const funds=Object.entries(D.universe.funds);$('scope').innerHTML=`<p>登记 ${D.audit.members}；有效评分 ${D.audit.scored_symbols} 股；ETF全成分文件 ${funds.filter(([f,s])=>s.status.startsWith('full_issuer_')).length}/${funds.length}。当前快照回溯；OpenD ETF分类含部分REIT，未核实者保留缺口。非美股成员不纳入此美股研究。</p>`+funds.map(([f,s])=>`<p>${esc(f)}：${s.status.startsWith('full_issuer_')?`${s.members.length} 美股成员（完整来源筛选）`:'全成分未取得'}${s.source_url?` · <a href="${esc(s.source_url)}">发行人</a>`:''}</p>`).join('');$('split').innerHTML=$('version').value==='monthly'?'每个外层月初：最近252个已成熟交易日；末64日分两块用于sigmoid和名单检查。每行保留训练/校准末日。<br>外层：2026-01-01—实际末端':'训练：2024-10-03—2025-09-30<br>Sigmoid：2025-10-01—11-14<br>阈值/登记：2025-11-17—12-31<br>外层：2026-01-01—实际末端';}
async function boot(){try{let bytes=Uint8Array.from(atob($('payload').textContent.trim()),c=>c.charCodeAt(0));let stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));BUNDLE=JSON.parse(await new Response(stream).text());const initial=new URLSearchParams(location.search);if(['fixed','monthly'].includes(initial.get('version')))$('version').value=initial.get('version');D={...BUNDLE,...BUNDLE.versions[$('version').value]};showEvidence();const r=D.results.routes[ROUTE];$('threshold').value=r.threshold;$('end').value=D.audit.last;$('start').value=date(stamp(D.audit.last+'T00:00')-29*DAY);for(let id of ['start','end']){let v=initial.get(id);if(v&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&v>=minDate&&v<=maxDate)$(id).value=v;}if(['favorites','watch','qqq','etf','all'].includes(initial.get('pool')))$('pool').value=initial.get('pool');$('loading').hidden=true;$('app').hidden=false;
chooseStock(initial.get('symbol'));$('version').onchange=()=>{D={...BUNDLE,...BUNDLE.versions[$('version').value]};$('threshold').value=D.results.routes[ROUTE].threshold;showEvidence();render();};$('pool').onchange=()=>chooseStock(symbol);$('symbol').onchange=()=>{symbol=$('symbol').value;render();};for(let id of ['start','end','grain','threshold','target','entry','period'])$(id).onchange=render;
for(let btn of document.querySelectorAll('[data-days]'))btn.onclick=()=>{$('start').value=date(Math.max(T0,stamp($('end').value+'T00:00')-(+btn.dataset.days-1)*DAY));render();};$('twoYears').onclick=()=>{$('start').value=minDate;$('end').value=maxDate;render();};$('frozenPeriod').onclick=()=>{$('start').value=D.results.periods.test.first;$('end').value=D.results.periods.test.last;render();};$('reset').onclick=()=>{$('threshold').value=D.results.routes[ROUTE].threshold;$('target').value='0.03';$('entry').value='open';$('period').value='test';render();};
$('mini').onclick=e=>{let box=e.target.getBoundingClientRect(),center=T0+(e.clientX-box.left)/box.width*(T1-T0),span=stamp($('end').value+'T00:00')-stamp($('start').value+'T00:00');let start=Math.min(T1-DAY-span,Math.max(T0,center-span/2));$('start').value=date(start);$('end').value=date(start+span);render();};$('mini').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();let delta=e.key==='ArrowLeft'?-7:7,span=stamp($('end').value+'T00:00')-stamp($('start').value+'T00:00'),start=Math.min(T1-DAY-span,Math.max(T0,stamp($('start').value+'T00:00')+delta*DAY));$('start').value=date(start);$('end').value=date(start+span);render();}};for(let id of ['miniStart','miniEnd'])$(id).oninput=()=>{let a=Math.min(+$('miniStart').value,+$('miniEnd').value),b=Math.max(+$('miniStart').value,+$('miniEnd').value);$('start').value=date(T0+a*DAY);$('end').value=date(T0+b*DAY);render();};
$('stockRows').onclick=e=>{let b=e.target.closest('[data-stock]');if(b){symbol=b.dataset.stock;$('symbol').value=symbol;render();}};$('events').onclick=e=>{let b=e.target.closest('[data-day]');if(b){$('start').value=$('end').value=b.dataset.day;$('grain').value='hourly';render();}};
$('chart').onmousemove=e=>{if(!canvasMap)return;let box=e.target.getBoundingClientRect(),pos=e.clientX-box.left,{from,to,left,right}=canvasMap,t=from+(pos-left)/(right-left)*(to-from),daily=$('grain').value==='daily',b=chartBars.reduce((best,b)=>Math.abs(stamp(daily?b[0]+'T12:00':b[0])-t)<Math.abs(stamp(daily?best[0]+'T12:00':best[0])-t)?b:best,chartBars[0]);$('hover').textContent=daily?`${b[0]} 常规盘 · O ${b[1]} H ${b[2]} L ${b[3]} C ${b[4]} V ${b[5]}`:`${b[0]}—${b[1]} ET · ${({regular:'常规盘',pre:'盘前',post:'盘后',night:'夜盘'})[b[7]]} · O ${b[2]} H ${b[3]} L ${b[4]} C ${b[5]} V ${b[6]} · ${b[8]}根真实5m`;};
$('export').onclick=()=>{const rows=filtered.filter(r=>r.symbol===symbol).map(r=>({...r,model_version:$('version').value,evaluated_target:$('target').value,entry_reference:$('entry').value,selection_threshold:$('threshold').value,selected:r['score_'+ROUTE]>=+$('threshold').value,evaluated_hit:hit(r)})),cols=['model_version','evaluated_target','entry_reference','selection_threshold','selected','evaluated_hit','symbol','day','period','score_'+ROUTE,'reference','delayed_reference','mfe','mae','close_ret','night_ret','pre_ret','mfe_'+ROUTE+'_20','mfe_'+ROUTE+'_50','mfe_'+ROUTE+'_80','pre_trade_age_minutes','night_trade_age_minutes','night_span_minutes','feature_end','max_source_available','label_end','fold','train_end','calibration_end','enrolled_'+ROUTE];const csv='\ufeff'+[cols.join(','),...rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=u;a.download=ROUTE+'_'+symbol+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};new ResizeObserver(()=>{if(D&&symbol){mini();chart();}}).observe($('chart'));}catch(e){$('loading').textContent='无法加载：'+e.message;console.error(e);}}
boot();
</script></html>'''

def main():
    results=json.loads((OUT/'results.json').read_text());audit=json.loads((OUT/'audit.json').read_text());universe=json.loads((OUT/'universe.json').read_text())
    charts=json.loads((OUT/'charts.json').read_text());versions={}
    for key,rpath,ppath in [('fixed','results.json','predictions.parquet'),('monthly','adaptive_results.json','adaptive_predictions.parquet')]:
        pred=pd.read_parquet(OUT/ppath).drop(columns=['available_pool','signal_pre_up'],errors='ignore')
        versions[key]={'results':json.loads((OUT/rpath).read_text()),'predictions':json.loads(pred.to_json(orient='records',double_precision=15))}
    results=versions['monthly']['results']
    sessions=json.loads((OUT.parents[1]/'market_data/model_training_history_v1/calendar.json').read_text())
    data={'versions':versions,'audit':{k:v for k,v in audit.items() if k!='sources'},'universe':universe,'charts':charts,
          'sessions':{s['session_date']:s['duration_minutes'] for s in sessions['sessions']}}
    payload=base64.b64encode(gzip.compress(json.dumps(data,ensure_ascii=False,separators=(',',':')).encode(),compresslevel=6,mtime=0)).decode()
    for route,(title,question) in TITLES.items():
        html=TEMPLATE.replace('__TITLE__',title).replace('__QUESTION__',question).replace('__ROUTE__',route).replace('__PAYLOAD__',payload)
        (OUT/(route+'.html')).write_text(html)
    links=''.join(f'<tr><td><a href="{r}.html">{t}</a></td><td>{results["routes"][r]["summary"]["precision"]:.1%}</td><td>{results["routes"][r]["summary"]["n"]}</td><td>{len(results["routes"][r]["favorite_passed"])}/5</td><td>{"通过" if results["routes"][r]["pass"] else "未通过"}</td></tr>' for r,(t,q) in TITLES.items())
    index=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>夜盘与盘前研究 v2</title><style>body{{font:15px/1.65 system-ui;margin:40px auto;padding:0 20px;max-width:1000px;color:#222}}h1{{font-size:26px}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #aaa;padding:12px;text-align:left}}a{{color:inherit}}.scroll{{overflow:auto}}p{{max-width:75ch}}</style><h1>夜盘与盘前 → 当天上涨空间</h1><p>三个独立调试页面，可切换固定年度与按月更新版本，共用同一套真实5分钟行情、时间切分和 +3% 触及标签。09:25截止输入；09:30开盘价仅作为未来标签参考。</p><div class="scroll"><table><tr><th>路线 / 打开调试</th><th>Precision</th><th>外层信号数</th><th>特别关注达标股</th><th>增量验收</th></tr>{links}</table></div><p>请求最近两年：{audit['requested_start']}—{audit['requested_end']}；实际可评分 {audit['first']}—{audit['last']}。登记 {audit['members']} 股，具有可评分行 {audit['scored_symbols']} 股；各股覆盖不等，ETF成分范围仍有缺口。当前池回溯、已暴露历史，仅为历史前向回测，尚无独立前向验证。</p><p><a href="REPORT.md">完整研究结果</a> · <a href="PROTOCOL.md">运行前登记</a> · <a href="audit.json">覆盖审计</a></p><p>调试页采用图形和证据联动的 wireframe 结构；日期起止、30/60/90/180日、两年日K mini、全日时段标记和逐日失败复盘均可交互。改变参数仅为探索，不改变冻结验收。</p></html>'''
    (OUT/'index.html').write_text(index)
    print(json.dumps({'compressed_payload_mb':len(payload)/1e6,'pages':list(TITLES)}))

if __name__=='__main__':main()
