"use strict";
const {chromium}=require(process.env.MAP_PLAYWRIGHT_PATH || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert').strict;
const dir=__dirname,data=JSON.parse(fs.readFileSync(path.join(dir,'data.json'),'utf8'));
const out=path.join(dir,'quality_browser');fs.mkdirSync(out,{recursive:true});
function current(q){return q&&q.decision==='current'&&q.grade&&!q.preview&&(!q.expires_at||new Date(q.expires_at+'T23:59:59Z')>=new Date());}
async function main(){
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1512,height:1100},colorScheme:'light'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.join(dir,'index.html'));await page.waitForSelector('#research-grade');
 assert.equal(await page.evaluate(()=>window.__map.D.rows.length),data.rows.length);
 assert.ok((await page.locator('.nav [data-tab="research"]').getAttribute('class')).includes('active'),'default research view');assert.equal(await page.locator('#quality-filter-label').isVisible(),false,'formal quality filter hidden on preliminary screen');
 const meta=data.research_screen||{};assert.ok(meta.rule_version==='ai_research_screen_v1','actual screen dataset required');
 const core= data.rows.filter(r=>r.kind==='STOCK'&&['A+','A'].includes(r.research_screen?.grade));
 assert.equal(await page.locator('#research-table tbody tr').count(),Math.min(50,core.length),'default initial A+/A rows');
 // Expiry boundary: mutate one in-memory clone, assert core exclusion and all-list retention, then restore.
 const expiryProbe=core[0];assert.ok(expiryProbe,'expiry probe available');const oldExpiry=expiryProbe.research_screen.expires_at;await page.evaluate(({code})=>{const r=window.__map.D.rows.find(x=>x.code===code);r.research_screen.expires_at='2000-01-01';window.__map.render();}, {code:expiryProbe.code});assert.equal((await page.locator('#research-table tbody tr').allTextContents()).some(t=>t.includes(expiryProbe.symbol)),false,'expired initial grade excluded from core');await page.selectOption('#research-grade','all');await page.fill('#search',expiryProbe.code);assert.match(await page.locator('#research-table').innerText(),/初评已过期/,'expired initial record retained and labeled in all mode');await page.selectOption('#research-grade','core');await page.fill('#search','');await page.evaluate(({code,oldExpiry})=>{const r=window.__map.D.rows.find(x=>x.code===code);r.research_screen.expires_at=oldExpiry;window.__map.render();},{code:expiryProbe.code,oldExpiry});await page.selectOption('#research-grade','core');
 const stats=await page.locator('#research-stats').innerText();assert.match(stats,/已核查/);assert.match(await page.locator('#research-status').innerText(),/不代表质量评级完成度/);
 await page.screenshot({path:path.join(out,'research-screen-desktop.png'),fullPage:true});
 const getVisible=()=>page.locator('#research-table tbody tr').count();
 for(const [filter,predicate] of [['A+',r=>r.research_screen?.grade==='A+'],['A',r=>r.research_screen?.grade==='A'],['A-',r=>r.research_screen?.grade==='A-'],['B',r=>r.research_screen?.grade==='B'],['missing',r=>(!!r.research_screen||[1,2,3].includes(r.business.tier))&&(r.research_screen?.status==='needs_evidence'||!r.research_screen?.grade)]]){
  await page.selectOption('#research-grade',filter);const expected=data.rows.filter(r=>r.kind==='STOCK'&&predicate(r)).length;assert.equal(await getVisible(),Math.min(50,expected),filter+' filter');
 }
 await page.selectOption('#research-grade','verified');
 const verified=data.rows.filter(r=>r.kind==='STOCK'&&(r.research_screen?.status==='verified'||r.research_screen?.verified_grade));assert.equal(await getVisible(),Math.min(50,verified.length),'verified filter');
 await page.selectOption('#research-grade','core');assert.equal(await page.locator('#quality-filter-label').isVisible(),false,'formal quality filter remains hidden on preliminary screen');
 await page.selectOption('#research-grade','all');
 const candidates=data.rows.filter(r=>r.kind==='STOCK'&&([1,2,3].includes(r.business.tier)||!!r.research_screen));assert.equal(await getVisible(),Math.min(50,candidates.length),'all AI candidates list');
 assert.ok((await page.locator('#research-groups').innerText()).includes('不可相加'));assert.equal(await page.locator('#research-groups tbody tr').count(),Object.keys(meta.groups||{}).length,'group taxonomy coverage');
 const sample=core[0]||data.rows.find(r=>r.kind==='STOCK'&&r.research_screen);assert.ok(sample,'at least one screen record');
 await page.fill('#search',sample.code);await page.locator('#research-table [data-stock="'+sample.code+'"]').click();
 const detail=await page.locator('#stock-detail').innerText();assert.match(detail,/批量初评/);assert.match(detail,/逐股核查评级|质量评级/);assert.ok(!detail.includes('[object Object]'));
 await page.click('#close-stock');await page.fill('#search','');await page.selectOption('#research-grade','core');
 const csvDownload=page.waitForEvent('download');await page.click('#research-export');const csvPath=path.join(out,'research-current-filter.csv');await(await csvDownload).saveAs(csvPath);const csv=fs.readFileSync(csvPath,'utf8');assert.equal(csv.trim().split(/\r?\n/).length,core.length+1,'current initial-screen CSV contains filtered 296 names');for(const col of ['初评等级','初评状态','正式核查等级','行业','业务依据','财务时效','下一步动作','批次日期','规则版本'])assert.ok(csv.includes(col),col);
 // Official-rating core stays independently filterable at 17 current A+/A names.
 await page.click('[data-tab="quality"]');await page.selectOption('#quality-grade','core');assert.equal(await page.locator('#quality-filter-label').isVisible(),true,'formal quality filter available on verified tab');const verifiedCore=data.rows.filter(r=>r.kind==='STOCK'&&current(r.quality)&&['A+','A'].includes(r.quality.grade));assert.equal(verifiedCore.length,17,'formal verified core remains separate');assert.equal(await page.locator('#quality-table tbody tr').count(),17,'formal core table');
 // Low-confidence and financial-source-unknown details retain warnings and source links.
 const low=data.rows.find(r=>r.kind==='STOCK'&&r.research_screen?.confidence_low);assert.ok(low,'low-confidence input present');await page.click('[data-tab="research"]');await page.selectOption('#research-grade','all');await page.fill('#search',low.code);await page.locator('#research-table [data-stock="'+low.code+'"]').click();const lowDetail=await page.locator('#stock-detail').innerText();assert.match(lowDetail,/置信度低|低置信/);assert.ok(await page.locator('#stock-detail a[href]').count()>0,'official business source link in low-confidence detail');await page.screenshot({path:path.join(out,'research-screen-low-confidence-detail.png'),fullPage:false});await page.click('#close-stock');
 const unknown=data.rows.find(r=>r.kind==='STOCK'&&r.research_screen?.financial_freshness?.status==='source_unknown');assert.ok(unknown,'financial freshness unknown record present');await page.fill('#search',unknown.code);await page.locator('#research-table [data-stock="'+unknown.code+'"]').click();const unknownDetail=await page.locator('#stock-detail').innerText();assert.match(unknownDetail,/source_unknown|取得日期未知/);assert.ok(await page.locator('#stock-detail a[href]').count()>0,'business source link retained on financial-unknown detail');await page.click('#close-stock');
 const withMissing=data.rows.find(r=>r.kind==='STOCK'&&(r.quality?.missing||[]).length);assert.ok(withMissing,'formal review missing evidence record present');await page.fill('#search',withMissing.code);await page.locator('#research-table [data-stock="'+withMissing.code+'"]').click();const missingDetail=await page.locator('#stock-detail').innerText();assert.match(missingDetail,/待补：/);assert.ok(missingDetail.includes(withMissing.quality.missing[0]),'old official-review missing reasons visible');await page.click('#close-stock');
 await page.fill('#search','');await page.selectOption('#research-grade','core');
 // The full AI-related export remains independent of the new screen filters and search.
 await page.fill('#search','NVDA');await page.click('[data-tab="basket"]');await page.selectOption('#quality-grade','A+');const fullDownload=page.waitForEvent('download');await page.click('#basket-export');const fullPath=path.join(out,'all-ai-independent.csv');await(await fullDownload).saveAs(fullPath);assert.equal(fs.readFileSync(fullPath,'utf8').trim().split(/\r?\n/).length,data.summary.ai_related+1,'full AI export remains full pool');
 await page.setViewportSize({width:390,height:844});for(const tab of ['research','map','basket','quality','gaps','price','list','method']){await page.click('[data-tab="'+tab+'"]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow '+tab);}
 await page.click('[data-tab="research"]');await page.click('#reset');assert.equal(await page.inputValue('#research-grade'),'core','mobile screenshot reset preserves default core');await page.screenshot({path:path.join(out,'research-screen-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);const result={passed:true,source:'actual built index.html + data.json',desktop:'1512x1100',mobile:'390x844',research_screen:{rule_version:meta.rule_version,run_id:meta.run_id,as_of:meta.as_of,summary:meta.summary},default_core_count:core.length,verified_filter_count:verified.length,formal_verified_core_count:verifiedCore.length,low_confidence_example:low.code,financial_unknown_example:unknown.code,missing_evidence_example:withMissing.code,checks:['default A+/A research screen','17-name formal verified core remains separate','low-confidence and financially unknown detail/source links','previous formal-review missing evidence displayed','research coverage separate from formal quality completion','A+/A-/B/missing/verified filters','expired initial-grade boundary with in-memory-only mutation','formal quality filter is hidden in preliminary mode and available in verified mode','overlapping groups caveat','stock details show preliminary and verified ratings distinctly','screen-filter CSV includes reproducibility fields','all-AI CSV remains independent of search and screen filters','390px no page overflow across views'],errors};fs.writeFileSync(path.join(dir,'research_screen_browser_verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
}
main().catch(e=>{console.error(e);process.exit(1)});
