const {chromium}=require(process.env.MAP_PLAYWRIGHT_PATH || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert').strict;
const dir=__dirname, base=JSON.parse(fs.readFileSync(path.join(dir,'data.json'),'utf8'));
const out=path.join(dir,'quality_browser');fs.mkdirSync(out,{recursive:true});
const data=JSON.parse(JSON.stringify(base));
for(const r of data.rows)r.quality=null;
const sample=(grade,decision='current',extra={})=>({grade,decision,stage:'scaling',materiality:3,commercial:2,moat:1,risk_reviewed:true,reasons:['test-only synthetic fixture: AI revenue and competitive evidence reviewed'],missing:[],risks:['test-only: competition'],as_of:'2026-10-06',expires_at:'2026-11-05',review_trigger:'test trigger',sources:[{url:'https://investor.nvidia.com/',source_url:'https://investor.nvidia.com/',title:'TEST FIXTURE official link',published_at:'2026-08-26',observed_at:'2026-10-07',evidence:'test fixture only'}],financials:{latest_period_end:'2026-07-26',latest_filed:'2026-08-27',source_capture_at:'2026-10-07',metrics:{revenue:{value:46743,unit:'USD millions',period:'FY2027 Q2',start:'2026-04-28',end:'2026-07-26',filed:'2026-08-27',tag:'RevenueFromContractWithCustomerExcludingAssessedTax',source_url:'https://investor.nvidia.com/'},net_income:{value:26422,unit:'USD millions',period:'FY2027 Q2',end:'2026-07-26',filed:'2026-08-27'},operating_cashflow:{value:23900,unit:'USD millions',period:'FY2027 Q2',end:'2026-07-26',filed:'2026-08-27'},cash:{value:60000,unit:'USD millions',period:'FY2027 Q2',end:'2026-07-26',filed:'2026-08-27'},total_debt:{value:8000,unit:'USD millions',period:'FY2027 Q2',end:'2026-07-26',filed:'2026-08-27'}},derived:{revenue_yoy:{value:0.56,unit:'ratio',formula:'(current/prior)-1',period_end:'2026-07-26'},net_margin:{value:0.566,unit:'ratio',formula:'net income/revenue',period_end:'2026-07-26'},fcf:{value:22000,unit:'USD millions',formula:'CFO-capex',period_end:'2026-07-26'},fcf_margin:{value:47,unit:'ratio',formula:'FCF/revenue',period_end:'2026-07-26'}}},...extra});
for(const [symbol,q] of [['NVDA',sample('A')],['AAPL',sample('B')],['AAOI',sample('A-')],['AMD',sample('A','current',{expires_at:'2026-09-01'})]]){const r=data.rows.find(x=>x.symbol===symbol);if(r)r.quality=q;}
data.quality_rating={as_of:'2026-10-06',run_id:'TEST-FIXTURE-ONLY',first_run:true,rule_version:'test-fixture-v1',preview:false,summary:{},changes:[]};
const html=fs.readFileSync(path.join(dir,'template.html'),'utf8').replace('__DATA__',JSON.stringify(data).replace(/<\//g,'<\\/'));
const fixture=path.join(out,'fixture.html');fs.writeFileSync(fixture,html);
async function main(){
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1512,height:1100},colorScheme:'light'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+fixture);
 await page.waitForSelector('#board .group');
 assert.equal(await page.locator('#board .group').count(),13);
 assert.equal(await page.locator('#periphery .group').count(),3);
 assert.equal(await page.evaluate(()=>window.__map.D.rows.length),data.rows.length);
 await page.screenshot({path:path.join(out,'desktop-core-default.png'),fullPage:false});
 assert.equal(await page.locator('#quality-grade').inputValue(),'core');
 assert.equal(await page.evaluate(()=>window.__map.rows().length),1,'default core includes only fixture A/A+');
 await page.selectOption('#quality-grade','all');
 assert.equal(await page.evaluate(()=>window.__map.D.rows.length),data.rows.length);
 await page.selectOption('#quality-grade','A-');assert.equal(await page.evaluate(()=>window.__map.stockRows().length),1);
 await page.selectOption('#quality-grade','B');assert.equal(await page.evaluate(()=>window.__map.stockRows().length),1);
 await page.selectOption('#quality-grade','stale');assert.equal(await page.evaluate(()=>window.__map.stockRows().length),1);
 await page.selectOption('#quality-grade','pending');assert.ok(await page.evaluate(()=>window.__map.stockRows().length)>0);
 await page.selectOption('#quality-grade','core');await page.click('[data-tab="quality"]');
 assert.match(await page.locator('#quality-status').innerText(),/首轮评级/);
 await page.selectOption('#quality-grade','all');await page.fill('#search','NVDA');
 await page.locator('#quality-table [data-stock="US.NVDA"]').click();
 await page.locator('#stock-detail details summary').click();
 const qdetail=await page.locator('#stock-detail').innerText();
 for(const t of ['$467.4 亿','$264.2 亿','$239 亿','$220 亿','2026-08-27','2026-10-07','56%','复算口径与原始数据','RevenueFromContractWithCustomerExcludingAssessedTax','商业扩张期','3 · 重要AI增长动力','2 · 已有付费交付','1 · 有专用能力/客户绑定','强：盈利与自由现金流支持'])assert.ok(qdetail.includes(t),'detail value/date/audit data missing '+t);
 assert.ok(!qdetail.includes('[object Object]'));assert.match(qdetail,/估值：未评估/);
 await page.click('#close-stock');await page.click('#reset');
 const qcsvDL=page.waitForEvent('download');await page.click('#export');const qcsv=path.join(out,'quality-filter.csv');await (await qcsvDL).saveAs(qcsv);
 const qcsvText=fs.readFileSync(qcsv,'utf8');assert.match(qcsvText,/评级as_of/);assert.match(qcsvText,/资料取得日/);assert.match(qcsvText,/2026-10-07/);
 await page.selectOption('#pool','held');
 assert.equal(await page.evaluate(()=>window.__map.rows().length),data.summary.held);
 await page.selectOption('#pool','qqq');
 assert.equal(await page.evaluate(()=>window.__map.stockRows().length),101);
 await page.click('#reset');
 await page.click('[data-tab="basket"]');
 const aiRows=data.rows.filter(r=>r.kind==='STOCK'&&[1,2,3].includes(r.business.tier));
 assert.equal(aiRows.length,data.summary.ai_related);
 assert.match(await page.locator('#basket-status').innerText(),new RegExp('全池 '+aiRows.length+' 只'));
 assert.equal(await page.locator('#basket-table tbody tr').count(),Math.min(100,aiRows.length));
 await page.screenshot({path:path.join(out,'ai-list-desktop.png'),fullPage:false});
 await page.fill('#search','NVDA');
 const basketDL=page.waitForEvent('download');await page.click('#basket-export');
 const basketFile=path.join(out,'basket-download.tmp');await (await basketDL).saveAs(basketFile);
 const basketCsv=fs.readFileSync(basketFile,'utf8');fs.unlinkSync(basketFile);
 assert.equal(basketCsv.trim().split(/\r?\n/).length,aiRows.length+1,'basket export remains full list despite search');
 for(const r of data.rows.filter(r=>r.kind!=='STOCK'||![1,2,3].includes(r.business.tier)))assert.ok(!basketCsv.includes('"'+r.code+'",'));
 await page.click('#reset');await page.selectOption('#quality-grade','all');await page.selectOption('#grade','positive');
 assert.equal(await page.evaluate(()=>window.__map.stockRows().length),aiRows.length);
 await page.click('#reset');
 const reviewed=data.rows.find(r=>r.business.review_status==='official_review'&&r.business.tier>0);
 await page.fill('#search',reviewed.code);await page.locator('#basket-table [data-stock="'+reviewed.code+'"]').click();
 assert.match(await page.locator('#stock-detail').innerText(),/行业：|Codex 6 Luna/);
 assert.ok((await page.locator('#stock-detail').innerText()).includes(reviewed.business.reasons[0]));
 await page.click('#close-stock');await page.click('#reset');await page.click('[data-tab="map"]');
 await page.selectOption('#path','capex');
 assert.equal(await page.locator('#board .path-hit').count(),9);
 await page.locator('[data-group="optics"]').first().click();
 assert.match(await page.locator('#group-detail').innerText(),/光通信与光子器件/);
 await page.locator('#group-table [data-stock="US.AAOI"]').click();
 assert.match(await page.locator('#stock-detail').innerText(),/ao|官方|业务资料/i);
 await page.click('#close-stock');
 await page.click('[data-tab="gaps"]');
 assert.equal(await page.locator('#gap-list .gap-item').count(),data.summary.blind_direct);
 assert.ok(!await page.locator('#gap-list').innerText().then(s=>s.includes('GOOGL')));
 await page.fill('#search','NO_SUCH_STOCK_912');
 assert.match(await page.locator('#gap-list').innerText(),/没有/);
 await page.click('#reset');
 await page.click('[data-tab="price"]');
 assert.match(await page.locator('.price-controls').innerText(),/六只算力参考股/);
 assert.ok(await page.locator('#scatter circle').count()>20);
 assert.equal(await page.locator('#clusters .cluster').count(),6);
 const math=await page.evaluate(()=>({same:window.__map.pearson([1,2,3,4],[2,4,6,8]),opposite:window.__map.pearson([1,2,3,4],[-1,-2,-3,-4]),constant:window.__map.pearson([1,1,1],[2,3,4]),residual:window.__map.residual([3,5,7,9],[1,2,3,4])}));
 assert.equal(math.same,1);assert.equal(math.opposite,-1);assert.equal(math.constant,null);assert.ok(math.residual.every(x=>Math.abs(x)<1e-12));
 const correlation=await page.evaluate(()=>{let r=window.__map.D.rows.find(r=>r.symbol==='AAOI');return window.__map.metrics(r)});
 assert.ok(correlation.valid&&correlation.n>=20&&Math.abs(correlation.raw)<=1&&Math.abs(correlation.residual)<=1);
 await page.screenshot({path:path.join(out,'price-desktop.png'),fullPage:false});
 await page.locator('[data-days="30"]').click();
 const shortStart=new Date(data.price.default_end+'T00:00:00Z');shortStart.setUTCDate(shortStart.getUTCDate()-29);
 assert.ok((await page.locator('#price-caption').innerText()).includes(shortStart.toISOString().slice(0,10)));
 await page.fill('#start','2026-09-01');await page.fill('#end','2026-08-01');await page.click('#calculate');
 assert.match(await page.locator('#price-caption').innerText(),/日期无效/);
 await page.fill('#end',data.price.default_end);await page.locator('[data-days="90"]').click();
 await page.selectOption('#corr-kind','raw');
 await page.click('[data-tab="list"]');
 assert.equal(await page.locator('#all-table tbody tr').count(),100);
 await page.click('[data-page="all-table"][data-delta="1"]');
 assert.match(await page.locator('#all-table .pages').innerText(),/2 \/ /);
 await page.fill('#search','NVDA');
 assert.ok(await page.locator('#all-table tbody tr').count()>=1);
 const dl=page.waitForEvent('download');await page.click('#export');const download=await dl;
 const csv=path.join(out,'csv-download.tmp');await download.saveAs(csv);assert.match(fs.readFileSync(csv,'utf8'),/US.NVDA/);fs.unlinkSync(csv);
 const jsonDL=page.waitForEvent('download');await page.click('#export-json');const j=await jsonDL;const jp=path.join(out,'json-download.tmp');await j.saveAs(jp);assert.equal(JSON.parse(fs.readFileSync(jp,'utf8').replace(/^\uFEFF/,'' )).rows.length,data.rows.length);fs.unlinkSync(jp);
 await page.click('#reset');await page.click('[data-tab="method"]');
 assert.match(await page.locator('#anomalies').innerText(),/Consumer Staples/);
 assert.equal(await page.locator('#fund-table tbody tr').count(),data.summary.funds);
 assert.match(await page.locator('#label-review-summary').innerText(),new RegExp('AI 等级覆盖 '+data.summary.graded));
 const industryOnly=data.rows.find(r=>r.kind==='STOCK'&&r.business.tier===null&&r.business.review_status==='industry_screened');
 await page.click('[data-tab="list"]');await page.fill('#search',industryOnly.code);
 await page.locator('#all-table [data-stock="'+industryOnly.code+'"]').click();
 const industryDetail=await page.locator('#stock-detail').innerText();
 assert.ok(industryDetail.includes('待核实')&&industryDetail.includes('行业：'));
 await page.click('#close-stock');await page.click('#reset');
 await page.setViewportSize({width:390,height:844});
 for(const tab of ['map','basket','quality','gaps','price','list','method']){
  await page.click('[data-tab="'+tab+'"]');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'overflow '+tab);
 }
 await page.click('[data-tab="basket"]');await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(out,'ai-list-mobile.png'),fullPage:false});
 await page.click('[data-tab="map"]');await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(out,'mobile.png'),fullPage:false});
 await page.click('#theme');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');
 await page.screenshot({path:path.join(out,'mobile-dark.png'),fullPage:false});
 await page.click('[data-tab="price"]');await page.locator('#scatter').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(out,'price-mobile.png'),fullPage:false});
 assert.deepEqual(errors,[]);
 const result={passed:true,desktop:'1512x1100',mobile:'390x844',errors,correlation_AAOI:correlation,checks:['default core and all grade filters','quality detail values and distinct report/receipt dates','quality CSV metadata','expired grade excluded from core','all pools and counts','all evidenced AI stock list and full CSV despite filtering','positive grade filter','new official evidence drilldown','industry-only grades remain unknown','industry paths and member drilldown','issuer-deduplicated gaps','empty states','explicit six-stock price comparison','date range and validation','raw and QQQ residual correlations','fixed six historical clusters','pagination','CSV and JSON download','coverage anomalies','light and dark themes','all six tabs mobile overflow','offline single HTML']};
 fs.writeFileSync(path.join(out,'fixture_verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
}
main().catch(e=>{console.error(e);process.exit(1)});
