const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {chromium}=require('/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=__dirname;
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8768/analysis/stock_behavior_description_v3/index.html',{waitUntil:'load'});await page.waitForFunction(()=>window.audit);
 assert.equal(await page.locator('.card').count(),55);assert.equal(await page.locator('.metric-line').count(),165);
 assert.equal(await page.locator('[data-metric="quietUp"]').count(),0);assert.equal(await page.locator('#sort option[value^="quietUp"]').count(),0);
 assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#grid')).gridTemplateColumns.split(' ').length),3);
 let onScreen=await page.evaluate(()=>Array.from(document.querySelectorAll('.card')).filter(c=>{let b=c.querySelector('.chart').getBoundingClientRect(),m=c.querySelector('.metric-lines').getBoundingClientRect();return b.top>=0&&m.bottom<=innerHeight}).length);
 assert(onScreen>=6,'Six complete charts and metric strips on desktop: '+onScreen);
 assert(await page.locator('.card').first().locator('.daily-candle').count()>0);assert(await page.locator('.card').first().locator('.weekly-candle').count()>0);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'comparison-desktop.png')});
 // Compare the two button groups against independent least-squares slopes from raw closes.
 const halfBaseline=await page.evaluate(()=>{
  const {data,state,calendars}=audit;
  const signs=data.records.map(r=>{
   const cal=calendars[r.code.split('.')[0]],rows=data.prices.records[r.code].filter(b=>b[0]>=state.from&&b[0]<=state.end),lookup=new Map(rows.map(b=>[b[0],b[4]]));
   const days=[...new Set([...rows.map(b=>b[0]),...cal.days.filter(d=>d>=state.from&&d<=state.end)])].sort(),cut=Math.floor(days.length/2);
   const slopes=[days.slice(0,cut),days.slice(cut)].map(a=>{
    if(state.from<cal.start||state.end>cal.end||a.length<2||a.some(d=>!lookup.has(d)))return null;
    const n=a.length,y=a.map(d=>Math.log(lookup.get(d))),sx=n*(n-1)/2,sxx=n*(n-1)*(2*n-1)/6,sy=y.reduce((a,b)=>a+b,0),sxy=y.reduce((a,v,i)=>a+i*v,0);
    return (n*sxy-sx*sy)/(n*sxx-sx*sx);
   });return {code:r.code,kind:r.kind,slopes};
  });return {signs,scales:audit.getScales(),from:state.from,end:state.end,descriptions:audit.getDescriptions()};
 });
 const halfExpected=(front,back)=>halfBaseline.signs.filter(r=>[front,back].every((v,i)=>v==='all'||r.slopes[i]!=null&&(v==='up'?r.slopes[i]>0:r.slopes[i]<0))).map(r=>r.code);
 const halfButton=(half,direction)=>page.locator(`[data-half-filter="${half}"][data-direction="${direction}"]`);
 for(const front of ['all','up','down'])for(const back of ['all','up','down']){
  await halfButton('front',front).click();await halfButton('back',back).click();
  assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),halfExpected(front,back),'Independent raw-close slope signs '+front+'/'+back);
  assert.equal(await page.locator('[data-half-filter="front"][aria-pressed="true"]').count(),1);assert.equal(await page.locator('[data-half-filter="back"][aria-pressed="true"]').count(),1);
  assert.deepEqual(await page.evaluate(()=>audit.getScales()),halfBaseline.scales);
 }
 await halfButton('front','down').click();await halfButton('back','up').click();
 const reversed=halfExpected('down','up');assert(reversed.length>0);
 await page.locator('#scope').selectOption('stock');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed.filter(c=>halfBaseline.signs.find(r=>r.code===c).kind==='STOCK'));
 await page.locator('#search').fill('MXL, CRDO, AMAT');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed.filter(c=>['US.MXL','US.CRDO','US.AMAT'].includes(c)));
 await page.locator('#clearFilters').click();assert.equal(await page.locator('.card').count(),55);assert.equal(await halfButton('front','all').getAttribute('aria-pressed'),'true');assert.equal(await halfButton('back','all').getAttribute('aria-pressed'),'true');
 await halfButton('front','down').focus();await page.keyboard.press('Enter');await halfButton('back','up').click();assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed);
 await page.locator('#showSlope').uncheck();assert.equal(await page.locator('.slope-label').count(),0);assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed);await page.locator('#showSlope').check();
 await page.locator('#showWeek').uncheck();assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed);await page.locator('#showWeek').check();
 await page.locator('#metricRange').selectOption('weekly');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed);await page.locator('#metricRange').selectOption('daily');
 const firstHalfCard=page.locator('.card').first();await firstHalfCard.locator('[data-pan="first"]').click();assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),reversed);
 await page.locator('[data-days="30"]').click();assert.equal(await page.evaluate(()=>audit.state.front),'down');assert.equal(await page.evaluate(()=>audit.state.back),'up');assert(await page.evaluate(()=>[...document.querySelectorAll('.card')].every(c=>+c.querySelector('[data-half="0"].slope-label').dataset.slope<0&&+c.querySelector('[data-half="1"].slope-label').dataset.slope>0)));
 await page.evaluate(()=>audit.setRange('2026-10-07','2026-10-07'));assert.equal(await page.locator('.card').count(),0);assert(await page.locator('#empty').isVisible());
 await page.locator('#clearFilters').click();assert.equal(await page.locator('.card').count(),55);await page.evaluate(({from,end})=>audit.setRange(from,end),halfBaseline);
 assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()),halfBaseline.descriptions);
 const upButton=value=>page.locator(`[data-up-filter="${value}"]`);
 const expectedUp=value=>halfBaseline.signs.filter(r=>{const s=halfBaseline.descriptions[r.code].shares;return value==='all'||s!=null&&(value==='gt70'?s.up>.7:value==='gt50'?s.up>.5:s.up<.5)}).map(r=>r.code);
 for(const value of ['gt70','gt50','lt50','all']){
  await upButton(value).click();assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),expectedUp(value));assert.equal(await page.locator('[data-up-filter][aria-pressed="true"]').count(),1);assert.deepEqual(await page.evaluate(()=>audit.getScales()),halfBaseline.scales);
  if(value==='gt50'||value==='lt50')assert(!(await page.evaluate(()=>audit.getFiltered())).includes('US.MU'),'Exactly 50% belongs to neither strict filter');
 }
 await upButton('gt70').click();await halfButton('front','down').click();await halfButton('back','up').click();await page.locator('#scope').selectOption('stock');await page.locator('#search').fill('MXL, CRDO, AMAT');
 assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),halfExpected('down','up').filter(c=>expectedUp('gt70').includes(c)&&['US.MXL','US.CRDO','US.AMAT'].includes(c)));
 await page.locator('#clearFilters').click();assert.equal(await upButton('all').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.card').count(),55);
 await upButton('gt50').focus();await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),expectedUp('gt50'));await page.locator('#clearFilters').click();
 await page.evaluate(()=>audit.setRange('2026-08-26','2026-10-07'));await upButton('gt70').click();
 for(const code of ['US.AMAT','US.MU','US.ARM']){assert.equal(await page.evaluate(c=>audit.getDescriptions()[c].shares.up,code),.7);assert(!(await page.evaluate(()=>audit.getFiltered())).includes(code),'Exactly 70% excluded from >70');}
 await upButton('gt50').click();for(const code of ['US.AMAT','US.MU','US.ARM'])assert((await page.evaluate(()=>audit.getFiltered())).includes(code));
 await page.evaluate(()=>audit.setRange('2026-10-07','2026-10-07'));assert.equal(await page.locator('.card').count(),0);await upButton('all').click();assert.equal(await page.locator('.card').count(),55);
 await page.locator('#clearFilters').click();await page.evaluate(({from,end})=>audit.setRange(from,end),halfBaseline);await upButton('gt70').click();
 await page.locator('#metricRange').selectOption('weekly');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),await page.evaluate(()=>audit.data.records.filter(r=>audit.getDescriptions()[r.code].shares?.up>.7).map(r=>r.code)));
 await page.locator('#metricRange').selectOption('daily');assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),expectedUp('gt70'));await page.locator('#clearFilters').click();
 assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()),halfBaseline.descriptions);
 const allScales=await page.evaluate(()=>audit.getScales());await page.locator('#search').fill('MXL, CRDO, AMAT');assert.deepEqual(await page.evaluate(()=>audit.getScales()),allScales);assert.equal(await page.locator('.card').count(),3);
 const mxl=page.locator('.card[data-code="US.MXL"]');assert.equal(await mxl.locator('[data-metric="up"] .metric-value').innerText(),'63.6% · 14/22');assert.equal(await mxl.locator('[data-metric="frequency"] .metric-value').innerText(),'2.93次/20日');assert.equal(await mxl.locator('[data-metric="amplitude"] .metric-value').innerText(),'15.2% · 5段');
 const beforeModel=await page.evaluate(()=>audit.getDescriptions()['US.MXL'].shares),beforeFolds=await page.evaluate(()=>audit.getDescriptions()['US.MXL'].folds),beforeScales=await page.evaluate(()=>audit.getScales()),domains=await page.evaluate(()=>[...audit.getViews()].map(([code,v])=>[code,v.layout.domain]));
 await page.locator('#showWeek').uncheck();assert.equal(await page.locator('.weekly-candle').count(),0);assert.deepEqual(await page.evaluate(()=>[...audit.getViews()].map(([code,v])=>[code,v.layout.domain])),domains);assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].shares),beforeModel);assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].folds),beforeFolds);await page.locator('#showWeek').check();
 let before=await page.evaluate(()=>{let l=audit.getViews().get('US.MXL').layout;return {offset:l.offset,from:l.from,end:l.end,weeklyFrom:l.weeklyFrom,domain:l.domain}});
 await mxl.locator('.chart').hover();await page.mouse.wheel(0,300);assert.deepEqual(await page.evaluate(()=>{let l=audit.getViews().get('US.MXL').layout;return {offset:l.offset,from:l.from,end:l.end,weeklyFrom:l.weeklyFrom,domain:l.domain}}),before);
 await mxl.locator('[data-pan="first"]').click();assert.equal(await page.evaluate(()=>audit.getViews().get('US.MXL').layout.offset),0);await mxl.locator('[data-pan="last"]').click();assert(await page.evaluate(()=>{let l=audit.getViews().get('US.MXL').layout;return l.offset===l.maxOffset}));
 await mxl.locator('svg').focus();await page.keyboard.press('ArrowLeft');assert(await mxl.locator('.probe').innerText().then(s=>s.includes('日 ')&&s.includes('周 ')));
 await page.locator('#metricRange').selectOption('weekly');assert(await page.locator('#metricHint').innerText().then(s=>s.includes('2025-08-14')));assert(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].shares.n)>22);
 assert.equal(await page.evaluate(()=>audit.getViews().get('US.MXL').layout.dailyDays),60);await page.locator('#metricRange').selectOption('daily');assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].shares),beforeModel);
 await page.locator('#sort').selectOption('up_desc');assert(await page.evaluate(()=>{let codes=audit.getFiltered(),d=audit.getDescriptions();return codes.every((c,i)=>!i||d[codes[i-1]].shares.up>=d[c].shares.up)}));
 for(const key of ['frequency','amplitude'])for(const direction of ['desc','asc']){
 await page.locator('#sort').selectOption(key+'_'+direction);assert(await page.evaluate(({key,direction})=>{const d=audit.getDescriptions(),codes=audit.getFiltered(),value=c=>key==='frequency'?d[c].folds?.frequency:d[c].folds?.amplitudeMedian;return codes.every((c,i)=>!i||value(c)==null||value(codes[i-1])!=null&&(direction==='desc'?value(codes[i-1])>=value(c):value(codes[i-1])<=value(c)))},{key,direction}));assert.deepEqual(await page.evaluate(()=>audit.getScales()),beforeScales);
 }
 const popupPromise=context.waitForEvent('page');await mxl.locator('.detail-link').click();const detail=await popupPromise;await detail.waitForLoadState('load');await detail.waitForFunction(()=>window.audit);detail.on('pageerror',e=>errors.push(e.message));assert(await detail.locator('#detailName').innerText().then(t=>t.includes('MXL')));assert.equal(await detail.locator('#frequency .scoreline').count(),3);assert.equal(await detail.locator('#windowFilter option[value="quietUp"]').count(),0);assert(!(await detail.locator('body').innerText()).includes('较平顺上行'));assert.equal(await detail.locator('#start').inputValue(),'2026-08-09');assert.equal(await detail.locator('#end').inputValue(),'2026-10-07');assert.equal(await detail.locator('#moves [data-wave]').count(),5);assert((await detail.locator('#frequency').innerText()).includes('2.93次/20日'));assert((await detail.locator('#frequency').innerText()).includes('15.2% · 5段'));
 const detailBefore=await detail.evaluate(()=>audit.getDescription().folds);await detail.locator('[data-wave="0"]').click();assert(await detail.locator('[data-evidence-shade]').count()>0);assert.deepEqual(await detail.evaluate(()=>audit.getDescription().folds),detailBefore);assert((await detail.locator('#evidenceInfo').innerText()).includes('完整波段'));
 await detail.locator('#windowFilter').selectOption('neither');assert.equal(await detail.locator('#windows [data-window]').count(),await detail.evaluate(()=>audit.getDescription().windows.filter(w=>!w.up).length));await detail.close();
 await page.locator('#clearFilters').click();assert.equal(await page.locator('.card').count(),55);await page.locator('#scope').selectOption('stock');assert.deepEqual(await page.evaluate(()=>audit.getScales()),allScales);assert.equal(await page.locator('.card').count(),38);await page.locator('#scope').selectOption('etf');assert.equal(await page.locator('.card').count(),17);await page.locator('#scope').selectOption('all');
 await page.locator('#search').fill('ZZZZZZ');assert.equal(await page.locator('.card').count(),0);assert(await page.locator('#empty').isVisible());await page.locator('#clearFilters').click();
 await page.locator('#end').fill('2026-07-31');await page.locator('#from').fill('2026-07-02');await page.locator('#applyDates').click();assert(await page.locator('#heading').innerText().then(s=>s==='日线 30 天 × 周线 210 天'));
 await page.locator('[data-days="60"]').click();assert.equal(await page.locator('#from').inputValue(),'2026-06-02');assert.equal(await page.locator('#end').inputValue(),'2026-07-31');
 await page.locator('#mini').focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#end').inputValue(),'2026-07-24');await page.keyboard.press('End');assert.equal(await page.locator('#end').inputValue(),'2026-10-07');
 await page.locator('details').filter({hasText:'探索描述规则'}).locator('summary').click();await page.locator('#windowSize').selectOption('10');await page.locator('#applyParams').click();assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].folds),beforeFolds);await page.locator('#threshold').selectOption('0.03');await page.locator('#applyParams').click();assert(await page.locator('#parameterStatus').innerText().then(s=>s.includes('探索')));assert.equal(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].shares.n),32);await page.locator('#resetParams').click();assert.deepEqual(await page.evaluate(()=>audit.getDescriptions()['US.MXL'].folds),beforeFolds);
 await page.locator('#search').fill('HK.03006, HK.07747');assert.equal(await page.locator('.card').count(),2);assert((await page.locator('.coverage-warning').first().innerText()).includes('10-06'));assert.equal(await page.locator('.card[data-code="HK.03006"] [data-metric="amplitude"] .metric-value').innerText(),'— · 无完整波段');await page.locator('#clearFilters').click();
 await page.setViewportSize({width:1050,height:1000});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#grid')).gridTemplateColumns.split(' ').length),2);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#grid')).gridTemplateColumns.split(' ').length),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await halfButton('front','up').click();await halfButton('back','down').click();assert.deepEqual(await page.evaluate(()=>audit.getFiltered()),halfExpected('up','down'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'half-filters-mobile.png')});await upButton('gt50').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'up-filter-mobile.png')});await page.locator('#clearFilters').click();
 await page.locator('#scope').selectOption('etf');await page.locator('#metricRange').selectOption('weekly');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#metricRange').selectOption('daily');await page.locator('#scope').selectOption('all');
 await page.locator('.card').first().scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollTo(0,document.querySelector('.card').getBoundingClientRect().top+scrollY-8));await page.screenshot({path:path.join(out,'comparison-mobile.png')});
 assert.equal(errors.length,0,errors.join(';'));assert(!(await page.locator('body').innerText()).includes('NaN'));assert.equal(await page.locator('[data-metric="repeated"]').count(),0);
 const offline=await browser.newContext(),filePage=await offline.newPage();await offline.setOffline(true);const requests=[];filePage.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await filePage.goto('file://'+path.join(out,'index.html'));await filePage.waitForFunction(()=>window.audit);assert.equal(await filePage.locator('.card').count(),55);assert.equal(requests.length,0);
 const report={status:'passed',view:'historical_comparison_wall_v3',browser:'Playwright Chromium headless',desktop:[1440,1000],tablet:[1050,1000],mobile:[390,844],complete_chart_metric_cards_on_first_screen:onScreen,errors,offline:true,
  checks:['55 all-member cards and 165 direction/frequency/amplitude bars','six charts plus metric strips on one screen','daily/week layers in each chart','reference dual range mechanism','MXL up unchanged, frequency 2.93/20d, full-wave amplitude 15.2%','multi-code search','sort frequency and amplitude high/low with unknown last; common scale unchanged','week hide preserves domain and metrics','explicit per-card pan','no wheel zoom','keyboard separate date probe','daily/weekly background metric range switching','detail link carries stock/date/parameters; full-wave evidence points to actual dates','stock/ETF/empty filters','four up-proportion filters and combined half/type/code filters','strict 50% and 70% boundaries checked on real historical windows','unknown proportions appear only in all; date/metric-scope changes recompute filters','up filter keyboard selection and clear reset; model outputs and scales unchanged','nine front/back direction combinations match independent raw-close fits','direction filters compose with type and code search','direction controls work with keyboard and reset together','hidden slopes, week layers, pan and weekly metric scope preserve daily-half filters','date changes refit half filters; missing/short slopes remain unknown','direction filters preserve model outputs and global metric scales','mobile direction button rows fit without overflow','shared dates and calendar shortcuts','fixed 2y mini keyboard','parameter exploration; up window leaves fold metrics unchanged','HK stale dates retained','3/2/1 responsive columns','wide and narrow no overflow','self-contained offline zero HTTP requests'],
  html_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'index.html'))).digest('hex')};
 fs.writeFileSync(path.join(out,'browser_verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
