import json
from pathlib import Path
OUT=Path(__file__).with_name('review_med_fin_gaps.json')
OBS='2026-10-06'
def src(url,title,evidence): return {'url':url,'title':title,'observed_at':OBS,'status':'luna_official_review','evidence':evidence}
def rec(code,name,industry,primary,groups,tier,reasons,sources,confidence='high',caveat=''): return {'code':'US.'+code,'name':name,'industry':industry,'primary':primary,'groups':groups,'tier':tier,'reasons':reasons,'sources':sources,'review_status':'unresolved' if tier is None else 'official_review','confidence':confidence,'caveat':caveat}
records=[
rec('GRAL','GRAIL, Inc.','多癌种早筛与液体活检','health',['health','data'],3,['Galleri多癌种早筛检测以cfDNA甲基化测序结合机器学习分类器判断是否存在癌症信号并预测来源；这是直接用于在售检测服务的AI诊断机制。'],[src('https://grail.com/galleri-test/the-test/','The Galleri Test','公司说明Galleri检测血液循环DNA片段，并通过机器学习算法区分健康/癌症来源、预测癌症信号起源；注明处方使用及检测限制。'),src('https://grail.com/press-releases/grail-submits-fda-premarket-approval-application-for-the-galleri-multi-cancer-early-detection-test/','GRAIL Submits FDA Premarket Approval Application','发行人描述其多癌早筛平台结合测序、机器学习、软件和自动化。')],'high','机器学习是检测技术机制，但FDA审批、临床效用和商业采用仍有不确定性。'),
rec('NEO','NeoGenomics, Inc.','肿瘤检测与数字病理服务','health',['health','data'],3,['公司将全切片成像与AI驱动图像分析用于肿瘤病理服务，并向药企提供AI图像分析/空间分析及训练数据，构成可识别的临床和研究服务能力。'],[src('https://www.neogenomics.com/providers/pathology-solutions/digital-pathology','Digital Pathology','NeoGenomics称其在病理服务中结合全切片影像和AI驱动分析，并已部署云端HALO AP平台以扩展第三方/自研AI工具。'),src('https://www.neogenomics.com/spatial-analysis-services','Spatial Analysis Services','Paletrra服务将AI图像分析与空间组学结合；提供单细胞分析等肿瘤研究服务。'),src('https://www.neogenomics.com/oncology-data-solutions','Oncology Data Solutions','公司提供超过250万张数字病理图像供客户机器学习和AI模型训练。')],'high','产品是癌症诊断/药企服务中的AI工作流与数据，不代表单独AI软件收入。'),
rec('WGS','GeneDx Holdings Corp.','罕见病基因检测与AI变异解读','health',['health','data'],3,['GeneDx把专有稀有病基因组数据与AI驱动的变异排序器结合，用于帮助临床遗传学家更快优先筛查致病变异并辅助诊断。'],[src('https://ir.genedx.com/','GeneDx Investor Relations','发行人介绍GeneDx Infinity临床基因组数据集，并称其支持AI驱动基因组智能及精准诊断。'),src('https://ir.genedx.com/node/11986/pdf','GeneDx Presents AI-Powered Variant Ranker','发行人介绍自有MIMI AI-based variant ranker，报告其对致病/可能致病变异排序并减少人工解读时间。')],'high','AI变异排序服务于检测解读流程；需继续验证AI功能与诊断收入贡献。'),
rec('QSI','Quantum-Si Incorporated','单分子蛋白测序仪与蛋白组学分析','health',['health','data'],2,['发行人将Biovista的AI可视化/关联分析工具许可并集成到Quantum-Si云分析套件，为Platinum蛋白测序结果提供疾病、蛋白与药物机制关联分析；属于AI数据分析配套。'],[src('https://www.quantum-si.com/press-releases/quantum-si-and-biovista-partner-to-provide-ai-driven-deep-proteomics-insights-from-the-platinum-next-generation-protein-sequence-platform-output/','Quantum-Si and Biovista Partner to Provide AI-Driven Proteomics Insights','公司公告称Biovista的AI可视化工具将集成进Quantum-Si云端分析套件，帮助客户从蛋白序列结果发现疾病、蛋白、药物作用机制关联。'),src('https://www.quantum-si.com/products/sequencing-solutions/','Protein Sequencing Solutions','公司产品包含Platinum仪器、试剂和软件，提供单分子蛋白测序及数据分析工作流。')],'medium','AI工具由合作方Biovista提供/授权并嵌入分析产品；Quantum-Si核心测序本身不是AI软件。'),
rec('PACB','Pacific Biosciences of California, Inc.','长读长基因测序与计算分析','health',['health','data'],3,['PacBio将Google合作开发的DeepConsensus深度学习共识算法部署到HiFi测序流程，并在2026年SPRQ-Nx商业推广中列为AI算法能力。'],[src('https://www.pacb.com/press_releases/pacbio-announces-second-quarter-2026-financial-results/','PacBio Announces Second Quarter 2026 Financial Results','发行人称SPRQ-Nx已全球商业推广，采用与Google共同开发的AI-powered DeepConsensus共识算法改善HiFi读取。'),src('https://www.pacb.com/blog/improving-hifi-sequencing-accuracy-with-google-deepconsensus-and-alphaevolve/','Improving HiFi Accuracy with DeepConsensus','公司说明Revio系统使用由PacBio与Google AI Genomics团队合作开发的transformer深度学习模型。')],'high','算法嵌入公司测序流程的证据明确；测序设备/试剂仍是主营，AI的单独收入未披露。'),
rec('ILMN','Illumina, Inc.','基因测序与生物信息软件','health',['health','data','compute'],3,['Illumina销售DRAGEN二次分析与BioInsight软件平台；官方资料明确机器学习驱动变异判读、AI注释与可解释AI临床基因组解释功能。'],[src('https://developer.illumina.com/illumina-connected-annotations','Illumina Connected Annotations','产品页称BioInsight包含AI软件套件，DRAGEN二次分析由AI/机器学习驱动，另提供AI基因组注释和可解释AI变异解释。'),src('https://www.illumina.com/products/by-type/informatics-products.html','Illumina BioInsight Informatics Platform','Illumina列出BioInsight平台、AI模型训练数据与DRAGEN机器学习变异分析产品能力。')],'high','产品AI证据明确；需要区分软件与仪器/试剂收入规模。'),
rec('IRTC','iRhythm Technologies, Inc.','动态心电监测与AI心律诊断','health',['health','data'],3,['Zio心电监测服务结合长时间ECG与FDA-cleared深度学习算法，可自动检测/分类多类心律失常并由技术人员复核形成报告。'],[src('https://www.irhythmtech.com/us/en/solutions-services/fda-cleared-ai','FDA-Cleared Advanced AI for Zio ECG Monitors','公司称Zio服务采用FDA许可深度学习神经网络算法，识别13类心律失常并辅助技术人员分析持续ECG。'),src('https://go.irhythmtech.com/hubfs/Instructions%20for%20Use%20%28IFUs%29/US/2025/March%20Updates/LB10058.08%20Zio%20ECG%20Utilization%20Software%20%28ZEUS%29%20Instructions%20for%20Use.pdf','Zio ECG Utilization Software Instructions for Use','官方说明ECG deep-learning algorithm分析记录、检测心搏、节律及心率。')],'high','AI是诊断服务中的具体机制；最终报告含人工技术员审核，临床性能及服务收入另行评估。'),
rec('ALHC','Alignment Healthcare, Inc.','老年医疗保险与数据驱动照护','health',['health','data'],3,['Alignment的专有AVA Medicare Advantage平台使用机器学习/AI汇总临床、药房和利用率数据，预测住院/健康风险与照护缺口，并驱动会员及照护团队工作流。'],[src('https://ir.alignmenthealth.com/static-files/c3f548c5-f809-402d-9e05-373f7a89c6c2','Alignment Healthcare 2025 Annual Report','年报称AVA使用机器学习、AI及数据分析整合会员信息，产生风险洞察、提醒和建议，支持风险分层、照护管理等活动。'),src('https://ir.alignmenthealth.com/news-releases/news-release-details/alignment-healthcare-shows-how-earlier-coordinated-care-leads/','Alignment Healthcare 2025 Impact Report','发行人称AVA是自有AI平台，整合临床、药房和利用率数据，以更早识别风险和照护缺口。')],'high','AI应用于公司自营健康计划和照护运营，并非对外单独售卖的AI软件；经营受Medicare政策和医疗成本影响。'),
rec('LMND','Lemonade, Inc.','数字保险与自动化理赔','data',['data'],3,['公司将AI Jim索赔机器人部署在投保人理赔流程中，负责收集索赔、自动处理一部分简单案件并将复杂案件交由人工；属于明确AI驱动的保险业务机制。'],[src('https://www.lemonade.com/blog/file-theft-claim/','How to File a Claim After Your Stuff Gets Stolen','Lemonade说明AI Jim为理赔机器人，收集索赔信息并自动处理简单理赔；复杂案件由人工团队审查。'),src('https://marketing-edge-assets.lemonade.com/investor/reports/LMND%202025%20Annual%20Report%20Final%204.22.26.pdf','Lemonade 2025 Annual Report','公司年报称claims bot AI Jim可在数秒内支付或拒付部分索赔，复杂情况仍由人工审核。')],'high','AI用于公司自营数字保险流程而非独立出售AI软件；自动处理范围受理赔规则和人工复核约束。'),
rec('UPST','Upstart Holdings, Inc.','AI信用评估与贷款撮合平台','data',['data'],3,['Upstart以专有AI模型分析数千项特征预测借款人违约风险，并通过面向银行的Credit Decision API提供实时信用决策和风险定价；AI是主营平台机制。'],[src('https://www.upstart.com/lenders/credit-decision-api/','Upstart Credit Decision API','产品页称贷款机构可将Upstart AI承保技术接入现有流程，模型分析2500余变量并返回实时信用决策、风险定价和条款。'),src('https://ir.upstart.com/','Upstart Investor Relations','发行人将公司定义为AI lending marketplace，并披露AI模型、贷款量和还款数据规模。')],'high','AI核心机制证据直接；信贷周期、资金来源、监管和模型表现影响业务兑现。'),
]
records += [
rec('RELY','Remitly Global, Inc.','跨境汇款与金融科技平台','data',['data'],3,['Remitly将AI/机器学习用于全球支付网络的反欺诈、风控、动态定价与交易路由；公司披露其风控引擎是汇款平台基础功能。'],[src('https://ir.remitly.com/node/9936/html','Remitly Global Form 10-K','发行人称自有数据模型和AI/ML持续改进欺诈风险、定价、客户支持与营销；核心业务为跨境汇款。'),src('https://ir.remitly.com/static-files/ccf6712b-117e-45ce-8145-39f3b1f99d0f','Remitly Investor Presentation','发行人把AI和机器学习驱动的欺诈检测/风险管理引擎列为全球汇款网络基础组成，并说明交易路由和合规用途。')],'high','AI是内部支付风险与运营决策机制，非独立AI软件收入；转账业务及货币/监管因素仍主导公司表现。'),
rec('SEZL','Sezzle Inc.','先买后付与数字支付','data',['data'],3,['SEC附件的发行人演示披露AI支持聊天机器人、AI购物助手以及以AI嵌入平台流程；公司也披露专有承保策略用于消费者风险/消费额度决策，构成具体面向用户和信贷工作流的AI机制。'],[src('https://www.sec.gov/Archives/edgar/data/1662991/000166299126000132/sezl-20260812ex9901.htm','Sezzle Overview Presentation August 2026','发行人称AI支持聊天机器人解决68%咨询，AI购物助手已向80% Sezzle Anywhere用户开放，并称专有承保模型分配消费额度。'),src('https://www.sec.gov/Archives/edgar/data/1662991/000166299126000032/sezl-20260306ex9901.htm','Sezzle Overview Presentation March 2026','发行人列出专有AI支持机器人、AI购物助手、争议处理代理和用户基础Embedding模型，分别说明实时上线/计划状态。')],'high','公司核心收入来自支付和BNPL信贷；需将客服/购物AI功能与承保模型分开看待，且部分功能阶段不同。'),
rec('CDNA','CareDx, Inc.','器官移植检测与临床决策支持','health',['health','data'],3,['CareDx商业推出AlloSure Plus AI派生风险分层工具，将供者来源cfDNA与传统临床指标组合，为每位肾移植患者计算排斥风险概率并可接入电子病历工作流。'],[src('https://www.caredx.com/professionals/allosure-plus','AlloSure Plus Testing for Kidney Transplants','官方产品页将AlloSure Plus描述为AI-derived风险分层工具，整合cfDNA、eGFR、蛋白尿和排斥史评估个体移植排斥风险。'),src('https://investors.caredx.com/files/doc_news/CareDx-Announces-Landmark-Data-in-AI-Powered-Transplant-Diagnostics-Showcased-in-Over-40-Abstracts-and-16-Oral-Presentations-at-the-2-4R3E3.pdf','CareDx Announces AlloSure Plus AI-Driven Diagnostic Platform','发行人公告说明AlloSure Plus将AlloSure检测与传统工具整合为个性化排斥风险诊断平台。')],'high','AI诊断平台具体但仍需看临床采用、支付覆盖及对检测收入的贡献。'),
rec('CBLL','Ceribell, Inc.','床旁脑电监测与AI癫痫诊断','health',['health'],3,['Ceribell Clarity是机器学习云端算法，实时解释多通道EEG、输出癫痫负担估计和警报；发行人称设备具FDA许可AI癫痫检测能力。'],[src('https://ceribell.com/product/clarity/','Clarity AI Brain Monitoring','公司称Clarity机器学习算法每10秒解释EEG多通道数据并估计seizure burden，提供实时检测与警报。'),src('https://investors.ceribell.com/node/7221/pdf','FDA Clears Ceribell Clarity for Pediatric Patients','发行人公告称Clarity获FDA许可用于1岁及以上患者脑电癫痫检测，并说明训练和验证数据规模。')],'high','AI算法明确嵌入监测产品；需区分AI功能获批、医院采用与收入/临床结局。'),
rec('CARL','Carlsmed, Inc.','个性化脊柱手术规划与植入物','health',['health'],3,['aprevo个性化脊柱手术平台以AI影像分割、CT三维建模和既往结局数据生成患者专属手术计划/植入器械，并以AI分析术后数据。'],[src('https://carlsmed.com/aprevo-technology-platform/','aprevo Technology Platform','公司产品页说明规划软件结合AI分割和既往结局数据生成个性化计划/器械，术后由AI系统分析手术数据；注明在美FDA许可的适应症。'),src('https://investors.carlsmed.com/','Carlsmed Investor Relations','发行人将公司定位为商业阶段、AI-enabled个性化脊柱手术平台。')],'high','AI软件与定制植入物配套，临床采用和商业规模仍需验证。'),
rec('HTFL','Heartflow, Inc.','冠状动脉影像AI诊断软件','health',['health','data'],3,['Heartflow向临床销售FDA许可的AI医疗器械软件，将冠脉CTA转为个性化3D血管模型，并通过深度学习及计算流体力学提供FFRCT、斑块分析及血流/狭窄评估。'],[src('https://www.heartflow.com/indications/','Heartflow Analysis Indications for Use','发行人明确称Heartflow Analysis是用于临床冠心病影像定量/定性评估的AI医疗器械软件。'),src('https://ir.heartflow.com/','Heartflow Investor Relations','公司介绍商业化AI诊断平台，用单次冠脉CTA创建个性化3D心脏模型并输出血流、狭窄和斑块信息。')],'high','商业化AI医疗软件证据直接；临床结果、支付覆盖及竞争风险仍影响收入持续性。'),
rec('HYPR','Hyperfine, Inc.','便携式低场脑MRI与深度学习重建','health',['health','edge'],3,['Swoop为FDA许可的AI便携式脑MRI；Optive AI软件用深度学习降低超低场MRI图像噪声/模糊并改善重建质量，属于公司主产品的关键成像机制。'],[src('https://hyperfine.io/products/overview','Swoop Portable MRI System','产品页描述Swoop为AI驱动便携式脑MRI，Optive AI用于0.064T低场成像深度学习重建，提升图像清晰度和一致性。'),src('https://hyperfine.io/about/news/press-release-hyperfine-announces-fda-clearance-of-a-new-next-generation-swoop-system-powered-by-optive-ai-software-delivering-a-transformative-leap-in-image-quality','FDA Clearance of Next-Generation Swoop Powered by Optive AI','发行人称新一代Swoop已获得FDA许可并由Optive AI软件驱动。')],'high','AI成像产品明确；仍需关注设备采用、图像质量验证及公司商业化/现金状况。'),
rec('NPCE','NeuroPace, Inc.','癫痫反应性神经刺激设备','health',['health'],0,['核查RNS产品与患者说明：设备连续监测脑电、识别个体癫痫模式并自动响应实施神经刺激，但官方材料未将算法描述为AI、机器学习或深度学习；未建立本口径下的AI关联。'],[src('https://www.neuropace.com/patients/neuropace-rns-system/','NeuroPace RNS System','发行人称RNS监测脑活动、按个体癫痫模式识别并响应，提供脑电数据；页面未称相关控制算法为AI。'),src('https://www.neuropace.com/','NeuroPace Company Website','公司产品资料说明RNS为FDA批准的反应性神经刺激设备并提供个性化治疗；所查页面没有AI/ML表述。')],'low','仅据实际查阅的产品材料作有限负面判断；个性化闭环设备本身不自动等于AI。'),
rec('FTV','Fortive Corporation','工业测量软件与医疗工作流技术','data',['data'],None,['2025年报只笼统称公司将AI纳入“某些产品、服务和功能”，但未指明具名产品、AI机制、客户应用或商业化路径；仅此泛化披露不足以判定具体AI关联。'],[src('https://investors.fortive.com/sec-filings/all-sec-filings/content/0001659166-26-000007/ftv-20251231.htm','Fortive 2025 Form 10-K','年报称Fortive在部分产品/服务/功能中加入AI解决方案，同时列出业务包括工业测量、设施软件和临床工作流；没有标明具体AI产品或业务对应关系。')],'low','保留null而非把泛化AI风险披露当作已核实的产品级供应证据。'),
rec('BRKR','Bruker Corporation','质谱、核磁与生命科学分析软件','health',['health','data'],3,['Bruker产品/软件明确包含AI机制：ProteoScape中TIMSquant是AI定量算法，NMRtist为机器学习辅助蛋白核磁分析软件；适用于蛋白组和代谢组研究工作流。'],[src('https://www.bruker.com/de/news-and-events/news/2023/bruker-introduces-novel-4d-proteomics-timstof-capabilities.html','Bruker Introduces AI-Powered TIMSquant','发行人宣布将AI驱动、CCS支持的无标记定量算法整合至ProteoScape，应用于大规模蛋白组定量。'),src('https://www.bruker.com/en/products-and-solutions/mr/nmr-software/nmrtist.html','NMRtist AI-Supported Protein NMR Software','官方产品页说明NMRtist是云端AI辅助软件，利用机器学习自动完成蛋白NMR峰识别和共振指派。')],'high','具名AI软件/算法已经查明；硬件、生命科学工具及服务仍为多元主体，AI收入未单列。'),
rec('CTKB','Cytek Biosciences, Inc.','细胞分析与流式细胞术仪器/软件','health',['health'],3,['ImageStream IDEAS图像分析软件提供机器学习细胞群分类模块，Amnis AI选项以深度学习卷积神经网络分析细胞图像，属于生命科学研究仪器的具体AI功能。'],[src('https://cytekbio.com/pages/imagestream','ImageStream Imaging Flow Cytometers','Cytek官方产品页说明IDEAS软件机器学习模块用于细胞分类，Amnis AI选项采用深度学习CNNs分析图像。')],'high','产品AI功能清楚，主要仍是细胞分析仪器和软件；未披露AI单独收入。'),
rec('QTRX','Quanterix Corporation','超敏生物标志物检测与空间蛋白组学','health',['health'],3,['Quanterix SP-X成像分析系统的官方产品资料称其专有采集算法与机器学习优化图像分析的动态范围和信噪比，是具体分析设备功能。'],[src('https://www.quanterix.com/the-sp-x-imaging-and-analysis-system/','SP-X Imaging and Analysis System','公司产品页称SP-X优化图像分析使用专有采集算法与机器学习，以最大化动态范围和信噪比。')],'medium','机器学习是检测设备分析工作流的配套功能；尚未证实其为独立收入驱动。'),
rec('ALMR','Alamar Biosciences, Inc.','蛋白质组学检测与NULISA平台','health',['health'],None,['已读发行人S-1/A：公司在内部运营及软件开发使用AI，也在探索将机器学习/生成式AI融入NULISA数据软件以增加生物学洞见，但措辞属于探索/投入计划，未证明当前具体商业产品功能或客户使用。'],[src('https://investors.alamarbio.com/static-files/327442d1-882e-40ac-86bf-6f5a36226fbb','Alamar Biosciences Form S-1/A','发行人披露内部AI运营使用，并表示正探索用机器学习和生成式AI增强统计软件与NULISA数据洞见、进行定向投入；未确认已交付的产品AI功能。')],'low','未将内部效率或研发路线图作为现有AI产品证据，故保留null/unresolved。'),
rec('RMD','ResMed Inc.','睡眠呼吸设备与居家数字医疗','health',['health'],3,['Smart Comfort为FDA许可的AI数字医疗器械，利用ResMed专有机器学习和逾1亿晚去标识化睡眠数据，为AirSense 11 CPAP新用户推荐个性化舒适设置，已计划在myAir分阶段推出。'],[src('https://investor.resmed.com/news-events/press-releases/detail/413/resmed-receives-fda-clearance-for-personalized-therapy-comfort-settings-to-be-marketed-as-smart-comfort-an-ai-enabled-digital-medical-device-that-helps-personalize-cpap-therapy','ResMed Receives FDA Clearance for Smart Comfort','发行人称Smart Comfort获FDA许可，以专有机器学习模型及睡眠数据为AirSense 11 CPAP推荐个性化舒适设置；2026年起分阶段发布。'),src('https://investor.resmed.com/sec-filings/content/0000943819-26-000047/rmd-20260630.htm','ResMed FY2026 Form 10-K','最新年报称AI/ML已用于特定产品、软件解决方案和业务流程，并描述连接式医疗软件及设备业务。')],'high','具体产品与机制有官方依据；获准/推出不代表使用效果或单独营收已验证。'),
rec('BDX','Becton, Dickinson and Company','医疗器械、监护与自动化药房系统','health',['health'],3,['BD Acumen HPI使用机器学习波形算法可提前预测术中低血压；BD Incada连接护理平台已与Pyxis Pro药物分配系统提供AI辅助运营洞察，均为具名医疗产品能力。'],[src('https://www.bd.com/en-us/products-and-solutions/products/product-families/acumen-hpi-software','Acumen Hypotension Prediction Index Software','BD官方产品页称HPI软件由机器学习衍生，分析动脉波形预测低血压，可提前约15分钟提供AI决策支持。'),src('https://www.bd.com/en-us/dc/corporate/2025/bd-incada-platform','BD Incada Connected Care Platform','BD称Incada是AI-enabled云平台，现与Pyxis Pro提供药品库存、流程指标和可行动洞见。')],'high','属于医疗监护和药房工作流中的AI产品/功能；贡献比例未单列。'),
rec('EW','Edwards Lifesciences Corporation','结构性心脏病介入治疗与瓣膜','health',['health'],None,['核查发现Acumen HPI机器学习监护产品已随Critical Care业务于2024年出售给BD；Edwards当前聚焦结构性心脏治疗，已查官方材料未建立当前留存业务中具体AI产品或明确AI路径。'],[src('https://ir.edwards.com/news/news-details/2024/Edwards-Lifesciences-Completes-Sale-of-Critical-Care/default.aspx','Edwards Completes Sale of Critical Care','Edwards公告确认Critical Care产品组已出售给BD。'),src('https://www.edwards.com/healthcare-professionals/products-services/predictive-monitoring/hpi','Acumen HPI Product Page','官方页注明Critical Care产品组现属于BD，并引导最新资料至BD；该AI产品不应算作Edwards现有业务。')],'low','保留null/unresolved；仅确认历史AI业务归属，未据此给现有Edwards业务正分。'),
rec('ZBH','Zimmer Biomet Holdings, Inc.','骨科植入物、手术机器人与数字护理','health',['health'],3,['ZBEdge的WalkAI利用人工智能/机器学习预测患者术后90天步行速度风险；OrthoGrid Hip AI提供术中AI髋关节组件定位指导，构成具体临床软件能力。'],[src('https://www.zimmerbiomet.com/en/products-and-solutions/zb-edge.html','ZBEdge Dynamic Intelligence','官方资料称WalkAI用AI/ML为患者建立个体预测模型，预测术后90天步行速度并提示低结果风险。'),src('https://investor.zimmerbiomet.com/news-and-events/news/2026/02-25-2026-120701913','Zimmer Biomet AAOS 2026 Innovations','发行人列出OrthoGrid Hip AI为AI驱动、透视影像髋关节手术指导工具，提供术中组件定位辅助。')],'high','具名软件及机制已确认；数字功能与植入物/机器人销售的收入贡献未单列。'),
rec('DXCM','DexCom, Inc.','连续血糖监测与糖尿病数字健康','health',['health','data'],3,['Dexcom获选FDA TEMPO数字医疗试点，将实施AI血糖健康项目，融合G7/Stelo血糖与营养、活动、睡眠、压力等上下文数据，向医护和合资格用户提供个性化洞察。'],[src('https://investors.dexcom.com/news/news-details/2026/Dexcom-Announced-as-First-Participant-Selected-for-FDAs-TEMPO-Digital-Health-Devices-Pilot-Program/default.aspx','Dexcom Selected for FDA TEMPO Pilot','发行人称试点允许公司实施AI驱动血糖健康项目，整合G7/Stelo数据与上下文健康信息，提供更个性化洞察。'),src('https://investors.dexcom.com/news/news-details/2026/Dexcom-Enters-Next-Era-of-Continued-Innovation-With-Jake-Leach-as-President-and-Chief-Executive-Officer/default.aspx','Dexcom 2026 Innovation Priorities','发行人提及2026年组合中将推出AI驱动增强功能。')],'medium','证据支持具体试点/规划产品，规模化商业发布及临床效果仍待验证。'),
rec('REGN','Regeneron Pharmaceuticals, Inc.','生物制药与遗传学驱动药物研发','health',['health','data'],1,['Regeneron将基因组/蛋白组/EHR关联数据与TriNetX合作扩展，发行人称该数据将支持药物发现并使AI训练算法开发未来数字健康方案；这是具体研究数据到研发的间接链路，尚非具名商业AI药物产品。'],[src('https://investor.regeneron.com/news-releases/news-release-details/regeneron-collaborates-trinetx-access-de-identified-electronic/','Regeneron and TriNetX Data Collaboration','发行人称合作扩展连接基因组/蛋白组与约3亿人去标识EHR的数据集，以支持药物研发并赋能AI训练算法。'),src('https://www.regeneron.com/stories/teaching-machines','Teaching Machines to do New Tricks','公司介绍遗传学中心使用AI/ML分析遗传和临床数据、建模疾病并寻找新药靶点。')],'medium','为具体研发工具路径而非AI收入；临床转化、药物成功和经济价值均未验证。'),
rec('ALNY','Alnylam Pharmaceuticals, Inc.','RNA干扰疗法与核酸药物研发','health',['health'],1,['Alnylam与Inceptive合作，将对方生成式AI基础模型接入Alnylam RNAi研发引擎，探索模型mRNA靶点、优化siRNA设计与预测临床前候选；属于具体研发合作，尚未形成AI商业产品。'],[src('https://news.alnylam.com/rnai/articles/accelerating-future-rnai-drug-discovery-ai-0','Accelerating the Future of RNAi Drug Discovery with AI','发行人披露与Inceptive合作将其AI基础模型用于Alnylam RNAi药物发现，并探索靶点建模、化学修饰优化及预测候选分子。')],'medium','合作仍在探索/研发阶段，不能据此推断获批药物或收入已由AI带来。'),
rec('VRTX','Vertex Pharmaceuticals Incorporated','创新药研发与商业化','health',['health'],None,['查阅2026年年报及官方业务/合作材料：年报只披露将AI用于组织生产力与效率的一般性愿景；2018年与Genomics plc的机器学习研发合作已是历史合作，当前资料未证明它仍在运行或形成具体AI产品/研发项目。保留null。'],[src('https://investors.vrtx.com/static-files/ee741e5e-ad45-499b-9e61-e239f34ec3b7','Vertex 2025 Form 10-K','年报风险段称公司寻求用AI优化组织生产力和效率，但未指定具体AI药物设计产品或药物项目。'),src('https://investors.vrtx.com/news-releases/news-release-details/vertex-and-genomics-plc-establish-collaboration-use-human','Vertex and Genomics plc Machine-Learning Collaboration','公司2018年公告曾称与Genomics合作使用机器学习支持精准药物靶点发现；公告为多年期历史合作，未证明当前有效。')],'low','未把一般内部AI使用或已过期的合作公告计为当前具体药物研发关联。'),
rec('BKNG','Booking Holdings Inc.','在线旅游预订与旅行平台','applications',['applications','data'],3,['Booking.com已将AI Trip Planner嵌入住宿搜索与预订旅程；AI/机器学习推荐模型、生成式对话规划、智能筛选、评论摘要及客服/住宿方代理是具名商业平台功能。'],[src('https://news.booking.com/bookingcom-debuts-agentic-ai-innovations-adding-to-its-robust-suite-of-genai-tools-for-customers/','Booking.com Debuts Agentic AI Innovations','发行人2025年宣布Smart Messenger与Auto-Reply上线，并说明平台还包括AI Trip Support、生成式搜索及嵌入预订流程的AI功能。'),src('https://news.booking.com/bookingcom-launches-new-ai-trip-planner-to-enhance-travel-planning-experience/','Booking.com Launches AI Trip Planner','公司称Trip Planner结合机器学习推荐与LLM对话，可查询目的地/住宿并生成行程，深链至住宿预订。')],'high','具名产品/功能已商业推出；对Booking Holdings整体营收和利润的增量未单独披露。'),
rec('PDD','PDD Holdings Inc.','电商平台与商户服务','applications',['applications'],3,['PDD 2025年20-F说明平台用AI筛查商品上架、审查可疑商品，并持续语义分析买家评价；还描述扩大AI与大数据能力以开发平台功能。该机制直接用于核心电商平台的信任与安全工作流。'],[src('https://investor.pddholdings.com/static-files/e15edea4-5e6d-4740-808a-63a3dd1b2ce4','PDD Holdings 2025 Form 20-F','发行人披露平台以AI系统筛查商品信息、将可疑商品送进一步核查，并对买家评价进行语义分析；研发投入用于增强AI/大数据能力。')],'medium','具体AI平台机制明确，但披露未量化效果、独立收入或对海外Temu的适用程度。'),
rec('CMCSA','Comcast Corporation','宽带网络、媒体与家庭连接服务','data',['data','connect'],3,['Comcast向Xfinity客户提供AI安全/保护功能，并在自有网络运行中用AI识别故障、异常流量和停电导致的批量断网；网络数据算法用于提升安全、运维与恢复效率，存在可辨识的客户功能及业务路径。'],[src('https://corporate.comcast.com/xfinity-shield','Xfinity Shield','Comcast产品页称Xfinity Shield使用其网络与网关技术及AI，为家庭设备提供数字/实体安全保护。'),src('https://corporate.comcast.com/press/releases/comcast-leverages-ai-to-restore-service-faster-when-commercial-power-outages-impact-customers','Comcast Uses AI for Network Restoration','公司称全国部署的AI/ML技术利用电源和客户连接数据识别批量断网原因，改善风暴/停电后的宽带恢复。')],'high','AI功能有官网具体描述，但并非独立AI业务；网络、媒体及宽带仍是公司主体业务。'),
]

def write():
    payload=json.dumps({'agent':'codex / gpt-6-luna','records':records},ensure_ascii=False,indent=2)+'\n'
    tmp=OUT.with_suffix('.json.tmp')
    tmp.write_text(payload)
    tmp.replace(OUT)
if __name__=='__main__':
 write(); print('wrote',len(records))
