"""Build official-source cross-sector AI evidence labels for the source universe."""
import json
from pathlib import Path
OUT=Path(__file__).with_name('review_cross_sector.json')
OBS='2026-10-06'
def src(url,title,evidence): return {'url':url,'title':title,'observed_at':OBS,'status':'luna_official_review','evidence':evidence}
def rec(code,name,industry,primary,groups,tier,reasons,sources,status='official_review',confidence='medium',caveat=''):
 return {'code':'US.'+code,'name':name,'industry':industry,'primary':primary,'groups':groups,'tier':tier,'reasons':reasons,'sources':sources,'review_status':status,'confidence':confidence,'caveat':caveat}
records=[
 rec('ACMR','ACM Research','半导体制造设备','design',['design'],1,['官网确认其提供晶圆清洗、电镀和先进封装设备；可支持AI芯片相关制造与封装产能的普遍扩张，但公司资料没有把产品和AI专属客户/收入绑定。'],[src('https://www.acmr.com/','ACM Research | Wafer Fabrication Equipment','公司销售晶圆级/面板级封装和半导体制造设备，涵盖清洗、电镀等工序。')],'official_review','low','只依据半导体制造供给的一般链路给低强度间接分；未证实AI需求传导或营收占比。'),
 rec('ADEA','Adeia Inc.','半导体知识产权与先进封装','design',['design','connect'],2,['其混合键合/先进封装 IP 授权用于3D集成，并被公司与合作代工厂明确描述为AI加速器/HPC的重要使能技术。'],[src('https://investors.adeia.com/news-releases/news-release-details/adeia-and-umc-expand-long-term-collaboration-hybrid-bonding','Adeia and UMC Expand Long-Term Collaboration in Hybrid Bonding Technologies','Adeia与UMC延长半导体IP授权合作；公司资料称混合键合支持下一代逻辑、存储、AI加速器和HPC。'),src('https://adeia.com/semiconductor/advantages','Advantages of Hybrid Bonding','DBI混合键合提高互连密度与带宽效率，适配高性能计算和AI带宽需求。')],'official_review','high','业务也包括媒体娱乐IP；技术相关性不代表AI相关授权收入规模。'),
 rec('AIP','Arteris, Inc.','芯片互连IP软件','connect',['connect','compute'],3,['NoC片上互连IP被发行人披露用于AI加速器芯片设计，帮助AI计算芯片实现高带宽、低功耗数据传输。'],[src('https://ir.arteris.com/news-releases/news-release-details/arteris-selected-rain-ai-use-next-generation-ai','Arteris Selected by Rain AI for Use in the Next Generation of AI','Rain AI选择Arteris FlexNoC IP用于AI加速器系列；公告说明其互连IP支持AI计算的片上网格网络。'),src('https://www.arteris.com/solutions/','Advanced SoC Interconnect & IP Solutions','公司产品页将AI列为应用，称NoC IP提升AI/ML SoC的数据移动和集成性能。')],'official_review','high','设计IP相关不等于客户芯片商业成功或授权收入规模。'),
 rec('ALMU','Aeluma, Inc.','化合物半导体光子器件','optics',['optics','design'],3,['发行人披露面向AI数据通信/互连研发高速光探测器和激光器，获得最高3000万美元CHIPS R&D LOI支持AI与先进计算光子平台开发。'],[src('https://www.aeluma.com/news-media/press-releases/detail/114/aeluma-announces-fourth-quarter-and-full-fiscal-year-2026','Aeluma Announces FY2026 Results; CHIPS LOI for AI','公司将高速光探测器、激光器和AI数据通信光子互连列为近期开发方向，并披露CHIPS资助意向和商业化研发。'),src('https://www.aeluma.com/investors/sec-filings/all-sec-filings/content/0001213900-26-100584/ea0305364-10k_aeluma.htm','Aeluma FY2026 Form 10-K','年报说明公司开发用于AI datacom的光子/电子技术和光探测器、阵列、激光器等。')],'official_review','high','产品处于研发/资格验证与商业化阶段；LOI并非最终拨款或成熟收入。'),
 rec('AMBQ','Ambiq Micro','超低功耗边缘AI芯片','compute',['compute','edge'],3,['Apollo SoC、向量加速及HELIA/neuralSPOT软件栈用于设备端AI推理，面向可穿戴、医疗、工业和IoT边缘设备。'],[src('https://ambiq.com/news/ambiq-launches-heliacore-for-real-world-edge-ai-deployment/','Ambiq Launches heliaCORE for Edge AI Deployment','公司发布面向Apollo SoC的AI kernel/软件层并报告模型验证和边缘部署能力。'),src('https://ambiq.com/products/','Ambiq Products','Apollo SoC产品页明确列出向量加速AI并面向边缘设备推理。')],'official_review','high','AI应用芯片证据明确，不代表AI产品已占主要收入。'),
 rec('ACIW','ACI Worldwide','支付软件与反欺诈','data',['data','applications'],3,['发行人提供采用自学习机器学习、网络情报及生成式AI的支付欺诈管理产品，服务银行、商户和账单支付。'],[src('https://www.aciworldwide.com/solutions/machine-learning','Machine Learning | ACI Worldwide','ACI称其反欺诈产品使用自学习算法和自动模型更新以检测金融犯罪。'),src('https://www.aciworldwide.com/solutions/aci-fraud-management-merchants','Fraud Management for Merchants','产品页说明利用AI特征、网络智能及实时决策管理支付欺诈。')],'official_review','high','AI属于产品功能和客户价值，不等同于独立AI收入或业务占比。'),
 rec('AGX','Argan, Inc.','电力工程与发电设施EPC','energy',['energy','power'],1,['年报称电力业务承接发电站工程并服务数据中心运营商；投资者资料披露一个数据中心项目合同。可建立数据中心扩容带来的电力建设链路，但未确认AI数据中心或专属订单。'],[src('https://arganinc.com/wp-content/uploads/2026/04/Argan-2026-Annual-Report_SEARCHABLE.pdf','Argan FY2026 Annual Report','Power Segment提供电站工程、设备采购、施工和电气并网服务，国际业务客户包括主要数据中心运营商。'),src('https://arganinc.com/wp-content/uploads/2026/06/Argan-Investor-Presentation-June-2026-Final.pdf','Argan Investor Presentation June 2026','公司展示美国数据中心项目合同，合同价值1.25亿美元，包括热膨胀及储能罐制造。')],'official_review','medium','数据中心项目并未在资料中明确为AI项目；多元工程业务及项目进度影响兑现。'),
 rec('POWL','Powell Industries','中高压开关柜与配电系统','power',['power','energy'],2,['公司制造电力分配与控制系统；发行人披露数据中心和AI投资带来更大机会，并开发应对高算力数据中心电力需求的高压开关设备。'],[src('https://powellindustriesinc.gcs-web.com/static-files/5a2af01d-fbd5-4837-a64b-11212ea64dfa','Powell Industries Form 8-K / Q1 FY2026 materials','公司材料称数据中心建设和AI投资带来更大机会，且推出满足大型高算力数据中心供电需求的开关柜产品。'),src('https://powellindustriesinc.gcs-web.com/','Powell Industries Investor Relations','公司介绍其长期设计、制造和封装电力分配及控制设备系统。')],'official_review','medium','供电产品适配数据中心，不能仅凭此推算AI订单、收入占比或利润率。'),
 rec('ITRI','Itron, Inc.','智能电网与公用事业软件','energy',['energy','data'],3,['Itron推出Cloud AI计量数据管理产品，并将NVIDIA边缘AI和Microsoft Copilot集成到电网软件；明确用于停电洞察、需求预测、配网优化与公用事业运营。'],[src('https://investors.itron.com/news-releases/news-release-details/itron-introduces-iee-cloud-ai-enabling-grid-edge-use-cases','Itron Introduces IEE Cloud AI','发行人发布AI计量数据管理云服务，应用包括停电洞察、电网可见性、预测和异常检测。'),src('https://investors.itron.com/news-releases/news-release-details/itron-bring-nvidia-powered-artificial-intelligence-grid-edge','Itron to Bring NVIDIA-Powered AI to the Grid Edge','Itron与NVIDIA合作将边缘AI用于电网优化、能源需求预测和实时配网处理。')],'official_review','high','明确AI软件产品和电网赋能能力；需另行验证付费采用与收入贡献。'),
 rec('TT','Trane Technologies','数据中心制冷与热管理','power',['power'],3,['Trane公布面向AI工厂的高密度液冷/冷水机组/CDU与参考设计，产品设计针对AI数据中心热负荷。'],[src('https://www.trane.com/commercial/north-america/us/en/markets/data-centers.html','Data Center Cooling Solutions','Trane官网列出AI数据中心冷却策略、冷水机组、CDU、控制及服务。'),src('https://investors.tranetechnologies.com/news-and-events/news-releases/news-release-details/2026/Trane-Technologies-Demonstrates-Industry-First-800-Volt-Direct-Current-Chiller-for-Next-Generation-AI-Data-Centers/default.aspx','800V DC Chiller for AI Data Centers','Trane披露为下一代AI工厂设计的800V直流冷却系统实验室验证，3.5MW制冷能力。')],'official_review','high','产品/参考设计证据明确；实验演示不能等同规模商业订单。'),
]

records += [
 rec('PDYN','Palladyne AI Corp.','工业机器人与国防具身AI软件','edge',['edge','applications'],3,['公司销售Palladyne IQ闭环自主软件，使工业机器人在动态环境中进行感知、学习、推理和动作；另提供面向无人机/无人系统的边缘AI协同自主平台。'],[src('https://www.palladyneai.com/palladyne-iq-lp/','Palladyne IQ AI Software Platform','公司产品页说明IQ将AI推理、视觉/多传感器感知、边缘实时规划用于工业机器人复杂装配、检测、清洁和表面处理，并支持低代码训练。'),src('https://www.palladyneai.com/sector/aerospace-defense/','Palladyne AI Aerospace & Defense','发行人列出IQ、SwarmOS无人系统协同自主软件及BRAIN X2边缘AI飞行模块。')],'official_review','high','公司确有AI机器人软件及系统产品；商业化收入占比和不同业务贡献未拆分。'),
 rec('KDK','Kodiak AI, Inc.','自动驾驶卡车软件与系统','edge',['edge','compute','applications'],3,['Kodiak Driver是可部署的AI自动驾驶系统，采用多传感器感知、深度学习和神经网络处理道路环境，发行人称其已有无人驾驶货运卡车商业部署。'],[src('https://kodiak.ai/technology','The Kodiak Driver: the most advanced autonomous technology','公司说明Kodiak Driver将AI软件与模块化传感器硬件结合，多传感器感知及深度学习驱动驾驶决策。'),src('https://kodiak.ai/news/training-physical-ai-at-scale','Building Physical AI for Autonomous Driving at Scale','发行人介绍GigaFusionNet基础模型、多模态传感器输入及2026年3月末28辆无驾驶舱司机卡车商业运营。')],'official_review','high','AI自动驾驶系统及部署证据明确；安全验证、商业规模扩张和经济性仍需独立观察。'),
 rec('RR','Richtech Robotics Inc.','工业及服务机器人与具身AI','edge',['edge','applications','data'],3,['公司披露AI驱动服务机器人和工业机器人；DEX使用AI视觉感知、实时推理和NVIDIA仿真训练完成工业操作，且Data Services业务提供具身AI训练数据。'],[src('https://ir.richtechrobotics.com/news-releases/news-release-details/richtech-robotics-showcase-integrated-industrial-robotics','Richtech Robotics Integrated Industrial Robotics Ecosystem','公司公告称DEX为AI-enabled工业人形机器人，使用视觉、深度感知和环境理解与Titan 440协同执行工业任务。'),src('https://ir.richtechrobotics.com/static-files/778957e1-6ab8-40e9-a349-a16482278166','Richtech Robotics Form 10-K','年报说明DEX经NVIDIA Jetson运行实时AI感知、运动规划和决策，另以Data Services生产具身AI训练数据。')],'official_review','high','具体机器人、训练和数据产品路径明确；需分别评估部署数量、收入贡献及商业持续性。'),
 rec('SERV','Serve Robotics Inc.','自主配送与医疗服务机器人','edge',['edge','applications','data'],3,['Serve设计并运营在真实道路环境自主导航的配送机器人；公司公开将其称为Physical AI，并推出搭载边缘AI的交互机器人，2026年收购扩展至医院室内服务机器人。'],[src('https://ir.serverobotics.com/','Serve Robotics Investor Relations','发行人描述公司自行设计软硬件并运营自主机器人，在复杂、人类活动环境中导航和配送；披露已部署机器人规模及收购医院服务机器人业务。'),src('https://ir.serverobotics.com/news-events/news','Serve Robotics News','发行人宣布推出由Edge AI驱动的交互机器人，并将其作为物理AI机器人演示。')],'official_review','high','AI自主机器人产品与运营明确；公司披露的AI用语不代表基础模型供应商，盈利性和单位经济仍需另行评估。'),
 rec('GE','GE Aerospace','航空发动机与AI维修及运营软件','applications',['applications','data'],0,['官网/年报资料确认公司已在维修运营中部署AI叶片检查和AI材料预测工具，但这些是公司内部维修效率应用；所查材料未建立面向外部客户销售的AI产品或AI专属供给链路。'],[src('https://www.geaerospace.com/investor-relations/annual-report','GE Aerospace Annual Report 2025','公司披露内部MRO应用AI叶片检测及发动机维修范围预测，缩短转修时间；未将相关工具列为单独对外AI产品。'),src('https://www.geaerospace.com/sites/default/files/ai-fact-sheet.pdf','GE Aerospace AI Fact Sheet','发行人列举AI数字孪生用于内部零件预测/维修流程，及员工内部生成式AI平台。')],'official_review','low','仅记录所查具体AI用途但未建立AI供应链暴露；航空航天行业属性本身不加分。'),
 rec('HSAI','Hesai Group','自动驾驶与机器人激光雷达/感知设备','edge',['edge'],2,['发行人销售用于ADAS、L3/L4自动驾驶及机器人视觉的激光雷达和空间感知硬件，并提出面向Physical AI的空间智能产品；属于自动驾驶AI感知配套设备。'],[src('https://www.hesaitech.com/product/ot128/','OT128 Automotive-Grade Long-Range Lidar','公司称OT128为自动驾驶应用提供360度高分辨率感知数据，设计用于L2-L4车辆感知。'),src('https://www.hesaitech.com/','Hesai Global Leader in 3D Perception','官网产品组合包括自动驾驶和机器人用激光雷达及AI空间相机，并描述其作为智能车辆感知设备。')],'official_review','high','证据支持AI感知系统的硬件配套，不代表Hesai提供完整AI模型或自动驾驶决策系统。'),
 rec('GENB','Generate Biomedicines Inc.','生成式AI生物药设计与研发','health',['health','data','compute'],3,['公司将机器学习驱动的蛋白质生成模型与大规模实验整合，用于设计具有指定功能的新蛋白药物，并推进由Generate平台产生的临床候选药。'],[src('https://generatebiomedicines.com/generative-biology/','Generative Biology','公司说明机器学习模型从蛋白序列/结构中学习规律并生成抗体、酶、肽等新型蛋白治疗药物，实验数据反复训练和优化平台。'),src('https://investors.generatebiomedicines.com/','Generate Biomedicines Investor Relations','发行人称其为临床阶段生成生物公司，通过机器学习与大规模实验推进蛋白药物设计，列出临床阶段项目。')],'official_review','high','AI平台与药物发现属于主营技术路径；临床成功、上市和商业价值仍有较高不确定性。'),
 rec('KTOS','Kratos Defense & Security Solutions','无人机与国防自主AI系统','edge',['edge','applications'],3,['Kratos披露在XQ-58 Valkyrie等无人作战飞机上使用AI和自主能力，并与Shield AI完成机载Hivemind AI飞行测试、推进系统集成产品化；公司还披露自研无人机AI/自主系统。'],[src('https://www.kratosdefense.com/unmanned-systems/air/uncrewed-tactical-aircraft/xq-58a','XQ-58 Valkyrie','官方产品页称Valkyrie使用自主能力和AI，可独立行动或参与有人/无人协同作战。'),src('https://www.kratosdefense.com/newsroom/kratos-and-shield-ai-conduct-ai-piloted-flights-on-the-kratos-tactical-firejet','Kratos and Shield AI Conduct AI-Piloted Flights','发行人宣布Shield AI的Hivemind已在Kratos Tactical Firejet上完成AI飞行测试，双方推进机载集成产品化。')],'official_review','high','无人平台与AI自主能力存在明确产品/集成证据；AI合作方技术与Kratos自研技术需区分，合同收入占比未披露。'),
 rec('NXT','Nextpower Inc.','太阳能电站与AI机器人巡检软件','applications',['applications','edge','energy'],3,['发行人公告称已启动AI与机器人业务，收购AI驱动的太阳能电站机器人巡检/火灾探测技术，可预测机械电气故障；另收购AI无人机图像建模IP及太阳能清洁机器人。'],[src('https://investors.nextracker.com/news/news-details/2025/Nextracker-Launches-New-AI-and-Robotics-Business-with-Technology-Acquisitions-and-New-Executive-Appointment/default.aspx','Nextracker Launches AI and Robotics Business','发行人披露AI/机器人业务、收购OnSight AI预测维护巡检与火灾检测系统、SenseHawk AI无人机建模IP和Amir Robotics清洁机器人。'),src('https://investors.nextracker.com/overview/','Nextpower Corporate Overview','公司目前将AI驱动自动化和智能控制软件列入其太阳能发电技术平台。')],'official_review','high','有具体AI巡检/预测维护及机器人产品资产；新业务收入、部署节奏和对原有跟踪器业务贡献尚未拆分。'),
 rec('AADX','Applied Aerospace & Defense','航空航天与国防制造','adjacent',['adjacent'],0,['查阅发行人投资者资料，确认其提供航空航天/国防复杂硬件设计、工程及垂直整合制造；所查业务介绍未建立AI产品、AI专属供货或客户项目关联。'],[src('https://investors.applied-ad.com/','Applied Aerospace & Defense Investor Relations','发行人说明其制造空间、航空防务及C5ISR/精确打击系统复杂硬件；该公司介绍未提及AI产品或AI专属客户项目。')],'official_review','low','只有国防制造行业信息，不将行业本身作为AI关联证据；需获得具体项目资料后再评估。'),
]

records += [
 rec('ABCL','AbCellera Biologics','抗体药物发现与生物技术','health',['health','data'],2,['发行人历史合作公告明确其抗体发现平台使用AI、机器学习和大规模数据分析；现有资料未证明该能力现阶段对应的产品收入或当前合作规模。'],[src('https://investors.abcellera.com/news/news-releases/2021/AbCellera-and-Empirico-Announce-Strategic-Multi-Target-Antibody-Discovery-Collaboration/default.aspx','AbCellera and Empirico Announce Strategic Multi-Target Antibody Discovery Collaboration','2021年发行人公告称AbCellera将使用AI驱动的抗体发现技术分析自然免疫反应，并结合机器学习与大规模数据发现治疗性抗体。')],'official_review','medium','AI技术证据为历史合作披露；并未核实当期商业化产品/收入贡献。'),
 rec('ABSI','Absci Corporation','生成式AI生物药发现','health',['health','data'],3,['公司将生成式AI药物设计与湿实验验证整合为AI drug creation平台，并披露该平台产出的自有生物药管线和合作项目。'],[src('https://www.absci.com/our-pipeline/','Absci Biologics Pipeline','发行人称其生物药管线展示AI drug creation平台能力，并列示ABS-201临床阶段候选药及其他项目。'),src('https://www.absci.com/','Absci | AI Drug Creation','公司首页将AI驱动药物创造与实验室验证作为核心平台能力。')],'official_review','high','平台/管线证据明确；药物临床成功、商业化和收入尚不确定。'),
 rec('ATEC','Alphatec Holdings','脊柱手术影像与临床软件','health',['health','applications'],3,['公司商业推出EOS Insight云平台，使用AI进行脊柱对齐评估、3D手术规划模拟和术中对照，且公告确认首家客户实施及手术。'],[src('https://investors.alphatecspine.com/press-releases/news-details/2024/ATEC-Launches-EOS-InsightTM-an-End-To-End-Spine-Surgery-Platform-Powered-by-EOS-Imaging-and-AI/default.aspx','ATEC Launches EOS Insight, an End-To-End Spine Surgery Platform Powered by EOS Imaging and AI','发行人称平台已商业推出、完成首个客户实施；应用包括AI对齐评估、3D手术规划模拟、术中比对和术后分析。')],'official_review','high','官方已披露商业推出及首例使用，不代表平台收入规模或临床结果改善已充分验证。'),
 rec('SENS','Senseonics Holdings','连续血糖监测医疗器械','health',['health'],0,['核查发行人CGM与AID合作公告：Senseonics提供连续血糖传感器，twiist Loop剂量算法由合作方系统提供；未建立Senseonics自身AI产品或AI专属供给路径。'],[src('https://www.senseonics.com/investor-relations/news-releases/2025/04-29-2025-123057707','Sequel Med Tech and Senseonics Integrate Technologies to Create First Automated Insulin Delivery System','公告将Senseonics定位为长期植入式CGM提供方，并明确AID系统由Sequel的twiist系统及其算法驱动；没有说明算法属于Senseonics或AI。')],'official_review','low','该合作证明传感器用于闭环给药生态，但没有证据将合作方算法归属为Senseonics的AI供给。'),
 rec('CGNX','Cognex Corporation','工业机器视觉与检测','edge',['edge','applications'],3,['公司销售嵌入式AI视觉系统及深度学习软件，用于工厂自动化的缺陷检测、装配验证、分类和字符识别。'],[src('https://www.cognex.com/en-ie/vidi-deep-learning','VisionPro Deep Learning','公司将VisionPro Deep Learning定义为AI图像分析软件，针对制造应用，包含缺陷检测、装配验证、分类和字符读取。'),src('https://www.cognex.com/products/machine-vision/3d-laser-profilers','3D Machine Vision Systems','公司介绍In-Sight L38为嵌入式AI 3D视觉系统，服务工业检测。')],'official_review','high','AI产品证据明确，但页面未披露AI相关营收占比。'),
 rec('DE','Deere & Company','农业机械与自主作业设备','edge',['edge','applications'],3,['John Deere自主拖拉机产品使用多摄像头感知和神经网络AI判断田间通行区域，构成发行人销售设备中的AI自主作业功能。'],[src('https://www.deere.com/en-us/products-solutions/tractors/autonomous-tractor/','Autonomous Tractor','公司产品说明披露16个摄像头提供360度感知，高速处理器分析影像，神经网络AI判断区域是否可通行；自主耕作解决方案可用于产品作业。')],'official_review','high','具体自主拖拉机产品证据；未拆分AI功能对设备销量/收入的贡献。'),
 rec('JCI','Johnson Controls International','数据中心热管理与楼宇系统','power',['power','energy'],2,['Johnson Controls发布面向吉瓦级AI工厂的热管理参考设计，包含冷水机组、冷却环路及高密度AI算力集群冷却方案。'],[src('https://www.johnsoncontrols.com/industries/data-centers/reference-designs','Johnson Controls Reference Designs for Gigawatt-Scale AI Factories','公司为AI工厂提供空气冷却、水冷及吸收式冷水机组参考设计，直接面向高密度AI工作负载和GPU冷却环路。'),src('https://investors.johnsoncontrols.com/news/news-details/2026/Johnson-Controls-launches-series-of-thermal-management-reference-design-guides-for-gigawatt-scale-AI-data-centers/default.aspx','JCI Launches Thermal Management Reference Designs for AI Data Centers','发行人新闻稿描述面向AI数据中心的冷却设计和下一代GPU技术冷却系统。')],'official_review','high','AI数据中心热管理供给证据明确；参考设计/产品适配不等同已签AI项目或收入金额。'),
 rec('EMR','Emerson Electric','工业自动化与工业AI软件','applications',['applications','data','edge'],3,['Emerson推出AspenTech AVA等面向工业运营的AI平台和AI顾问/代理，接入工业OT数据与自动化工作流，提供预测、诊断及运行建议。'],[src('https://www.emerson.com/en/corporate/news/2026/new-emerson-industrial-ai-platform-delivers-enterprise-scale-ai','New Emerson Industrial AI Platform Delivers Enterprise-Scale AI','发行人公告发布专为工业企业设计的AspenTech AVA AI平台，具备领域感知生成式AI并嵌入运营工作流。'),src('https://www.emerson.com/en/automation-systems/ovation/ovation-ai','Ovation AI-Enabled Applications','公司展示Ovation AI智能助手和AI agents，应用于电力/水务运营诊断、预测维护及运行决策。')],'official_review','high','AI软件和自动化集成证据明确；需单独量化软件收入及AI产品贡献。'),
 rec('BFLY','Butterfly Network','便携式超声影像与临床AI软件','health',['health','applications','edge'],3,['Butterfly发布Compass AI企业超声项目管理软件，且其超声设备集成AI图像采集引导和临床工作流功能。'],[src('https://ir.butterflynetwork.com/News/press-releases/news-details/2025/Butterfly-Network-Launches-Compass-AI-to-Power-the-Next-Generation-of-POCUS-Program-Management/default.aspx','Butterfly Network Launches Compass AI','发行人发布由AI驱动的企业超声软件，帮助医疗系统管理床旁超声项目并自动化工作流。'),src('https://www.butterflynetwork.com/','Butterfly iQ3 Point-of-Care Ultrasound','公司产品页称其超声设备整合AI、影像工具和软件。')],'official_review','high','产品证据明确；未核实AI软件独立收入或临床效果规模。'),
 rec('PRCT','PROCEPT BioRobotics','泌尿外科手术机器人','health',['health'],0,['核查发行人产品页与公司介绍：其产品为影像引导、计算机辅助规划和机器人水刀治疗；所查材料未建立AI功能或专用AI供给路径。'],[src('https://ir.procept-biorobotics.com/corporate-profile','PROCEPT BioRobotics Corporate Profile','公司介绍AQUABEAM为实时多维影像引导、个性化治疗规划和自动化机器人系统；所查页面未将产品描述为AI系统。'),src('https://www.procept-biorobotics.com/government-hospitals/aquabeam-robotic-system','AquaBeam Robotic System for BPH','官方产品页描述超声图像引导、计算机辅助规划及机器人水刀切除，未将其描述为AI。')],'official_review','low','仅代表所查官方材料没有建立AI关联，不否定其他未检索产品/能力。'),
]


records += [
 rec('SPXC','SPX Technologies','暖通制冷、冷却塔与工业检测','power',['power'],2,['发行人产品组合和财报明确提供数据中心冷却产品，并披露数据中心冷却业务扩产；这属于算力基础设施的热管理配套，但没有把订单单独指向AI数据中心。'],[src('https://www.sec.gov/Archives/edgar/data/88205/000008820526000052/q22026pressrelease.htm','SPX Technologies Reports Q2 2026 Results','发行人称数据中心收入产能及数据中心冷却业务规模扩大。'),src('https://spx.gcs-web.com/static-files/f84fba2e-d35a-451b-9002-80b2aadcecff','SPX Q4 2025 Earnings Presentation','公司称HVAC产能扩张支持数据中心冷却产品需求。')],'official_review','medium','证据针对数据中心制冷，未证明项目属于AI数据中心或AI相关销售占比。'),
 rec('GWW','W.W. Grainger','工业维护用品分销','adjacent',['adjacent'],0,['核查SEC年报及发行人投资者资料。Grainger披露在开发/部署AI能力用于自身运营及数字平台，但未确认可识别的AI供给产品、基础设施专属产品或具体AI客户供应路径。'],[src('https://www.sec.gov/Archives/edgar/data/277135/000027713526000011/gww-20251231.htm','W.W. Grainger 2025 Form 10-K','年报称公司正在向数字平台和内部运营加入AI能力，相关开发仍在进行且商业获益不确定；未建立面向AI产业链的具体供货路径。'),src('https://invest.grainger.com/home/','Grainger Investor Relations Corporate Profile','公司主营为MRO广品类分销与增值服务。')],'official_review','low','仅有内部采用/开发AI的公司风险披露，不应据此认定为AI产业链供给商。'),
 rec('LECO','Lincoln Electric Holdings','焊接设备与自动化系统','edge',['edge'],0,['核查发行人可持续发展/自动化资料，确认其提供焊接设备和自动化系统；检索到的材料没有建立AI专用产品、机器学习功能或具体AI客户供给路径。'],[src('https://sustainability.lincolnelectric.com/assets/documents/LE_SustainabilityReport2023.pdf','Lincoln Electric Sustainability Report 2023','公司介绍焊接自动化设备和系统旨在提高工艺一致性、安全与效率；所查章节未披露AI功能。')],'official_review','low','自动化设备本身不等于AI产品；结论限于实际查阅资料。'),
 rec('GRC','The Gorman-Rupp Company','工业与市政泵及泵系统','power',['power'],0,['官网可查到泵系统适用于数据中心相关应用，但已查的公司业务资料只证明通用泵/冷却基础设施供给，未建立AI专用设备或明确AI项目链路。'],[src('https://www.gormanrupp.com/pump-finder?hsLang=en','Gorman-Rupp Pump Finder','公司应用目录列出数据中心机架液冷消防泵应用，但未将该应用或产品标为AI专用。'),src('https://www.gormanrupp.com/en/gorman-rupp','Gorman-Rupp Company Profile','公司主要制造水、污水、工业、市政和消防等泵系统。')],'official_review','low','数据中心用途并不自动等同AI用途，未给正分。'),
 rec('AMSC','American Superconductor','电网电能质量与数据中心供电','power',['power','energy'],2,['发行人披露已向数据中心项目交付首批系统，并称AI基础设施扩张带动数据中心对韧性、高效电力系统的需求；其电网供电质量/控制产品属于供电部署环节。'],[src('https://ir.amsc.com/static-files/088585e3-ec02-4810-8445-9057602a390f','AMSC Annual Letter to Stockholders 2026','股东信称公司在FY2025第三季度首次向数据中心项目直接交付系统，并将AI基础设施扩张与数据中心电力韧性需求相联系。'),src('https://ir.amsc.com/news-releases/news-release-details/amsc-reports-fourth-quarter-and-fiscal-year-2025-financial','AMSC Reports Q4 and FY2025 Results','公司称第四季度订单接近1亿美元，其中包括公用事业市场数据中心需求。')],'official_review','medium','已确认数据中心项目交付和AI基础设施需求背景，但未确认具体交付项目为AI数据中心，也未披露AI相关收入占比。'),
 rec('EME','EMCOR Group','机电工程与关键设施施工','power',['power'],0,['核查发行人官网关键数据中心业务页面，确认其承建超大规模数据中心的电力、机械和通信设施；所查材料未将项目明确绑定AI数据中心或披露AI专属订单。'],[src('https://emcorgroup.com/missioncritical','EMCOR Mission Critical Data Center Capabilities','公司称提供超大规模数据中心的设计建设、低压安装、消防以及运维服务；页面未明确AI数据中心项目。')],'official_review','low','只证明数据中心基础设施服务，不将一般云/大数据客户推定为AI算力项目。'),
 rec('FIX','Comfort Systems USA','暖通与机电工程服务','power',['power'],None,['已查发行人投资者新闻/SEC业绩材料，证实其为建筑系统安装与维护服务商；当前检索未获得官方材料将其订单明确归于AI数据中心或其他特定AI价值链。'],[src('https://investors.comfortsystemsusa.com/news-releases','Comfort Systems USA Investor Relations News Releases','发行人新闻列表显示其主营建筑系统安装维护及经营业绩资料；已查页面无AI产品或AI数据中心项目细节。'),src('https://www.sec.gov/Archives/edgar/data/1035983/000110465926086255/fix-20260723xex99d1.htm','Comfort Systems USA Q2 2026 Results','公司公布业务和积压订单，但该材料未识别AI专属合同。')],'unresolved','low','已知HVAC/数据中心施工行业位置不足以建立AI链路；因此标证据不足而非正分或0。'),
 rec('MTZ','MasTec, Inc.','电力输送与数据中心建设','power',['power','energy'],2,['发行人投资者日资料明确将AI数据中心校园建设列为工程机会，列出场外电力、输电/变电、现场电气及数据厅施工等服务范围。'],[src('https://investors.mastec.com/static-files/7e7b1efe-549b-4ef1-bdf2-d77f681bbd3f','MasTec Investor Day 2026 Presentation','公司将AI数据中心校园建设管理列为机会，并列示发电/输电、通信、现场基础设施、数据厅建设等可提供能力。'),src('https://mastec.com/','MasTec Corporate','官网确认其数据中心业务提供电力、建设及通信一体化方案。')],'official_review','medium','官方明确描述AI数据中心施工机会，但不代表所有所列工程合同均为AI项目或已转化收入。'),
 rec('AVAV','AeroVironment','无人机、自主系统与国防AI','edge',['edge','applications'],3,['公司AI/自主决策产品页和P550系统披露AI自主飞行、目标识别与分类等功能，面向实际部署的无人机、反无人机及任务系统。'],[src('https://www.avinc.com/capabilities/ai-autonomy-decision-support/','AI, Autonomy & Decision Support','公司销售/集成AI驱动决策与自主能力，支持边缘任务情报、传感和多系统协作。'),src('https://www.avinc.com/solution/p550/','P550 Autonomous eVTOL UAS','公司产品页称P550集成AI自主功能进行物体检测/分类并执行自主飞行任务。')],'official_review','high','AI供给集中于国防用途；合同与收入节奏受国防采购和项目履约影响。'),
 rec('OMCL','Omnicell','医疗药品管理与药房自动化','health',['health','applications'],2,['公司官网介绍Titan XT与OmniSphere支持AI增强药品库存风险预测和主动决策，关联医疗机构药品管理；官方脚注明确该产品仍在开发、尚未普遍上市。'],[src('https://www.omnicell.com/points-of-care/titan-xt/','Titan XT Automated Dispensing Cabinet','公司称Titan XT具备AI-enabled intelligence以预测库存风险；页面脚注说明Titan XT/OmniSphere仍在开发且未普遍向客户提供。'),src('https://www.omnicell.com/central-pharmacy/','Omnicell Central Pharmacy Dispensing','公司介绍其药房机器人与药品自动化产品及AI-enabled OmniSphere洞察。')],'official_review','medium','AI功能属计划中的具体药品管理能力；官方说明仍在开发，不能等同已普遍商业化或AI收入。'),
]


records += [
 rec('NTRA','Natera, Inc.','精准医疗检测与AI生物数据平台','health',['health','data'],3,['发行人推出基于逾25万肿瘤外显子及百万级纵向血浆时间点的多模态AI基础模型平台，提供临床决策、患者模拟、试验匹配及治疗反应预测应用，并披露与NVIDIA扩展模型训练合作。'],[src('https://www.natera.com/company/news/natera-launches-proprietary-ai-foundation-models-to-accelerate-diagnostic-and-therapeutic-innovation/','Natera Launches Proprietary AI Foundation Models','发行人宣布自研AI基础模型及多项临床和药物开发应用，说明训练数据构成和具体应用场景。'),src('https://www.natera.com/company/news/natera-to-scale-ai-foundation-models-in-precision-medicine-with-nvidia/','Natera to Scale AI Foundation Models with NVIDIA','双方将Natera临床纵向数据及机器学习模型与NVIDIA算力结合，扩展精密医疗AI模型开发。')],'official_review','high','AI平台产品与开发证据明确；临床采用、支付和营收贡献需单独验证。'),
 rec('SDGR','Schrödinger, Inc.','计算化学与AI药物设计软件','health',['health','applications','compute'],3,['Schrödinger销售LiveDesign ML等软件，供药物研发团队训练、部署AI/机器学习分子性质模型，并推出AI驱动的RetroSynth合成路线设计工具。'],[src('https://www.schrodinger.com/platform/products/livedesign-ml/','LiveDesign ML','公司称产品用于小分子药物发现，支持AI/ML模型训练、验证、部署和性质预测。'),src('https://www.sec.gov/Archives/edgar/data/1490978/000149097826000009/sdgr-20251231xexx991.htm','Schrödinger 2025 Results and Platform Highlights','发行人披露AI驱动RetroSynth和LiveDesign与药企TuneLab工作流整合，平台结合物理模拟与AI设计药物候选物。')],'official_review','high','明确AI/ML研发软件产品；平台收入和公司自研药物管线应分别看待。'),
 rec('TEM','Tempus AI, Inc.','AI精准医疗诊断与临床数据平台','health',['health','data','applications'],3,['Tempus提供AI诊断、临床数据分析和生成式AI临床决策产品；公司披露已有FDA许可的ECG-AI产品及Next临床照护路径平台。'],[src('https://investors.tempus.com/','Tempus AI Investor Relations','公司将自身定位为通过AI推动精准医疗，介绍Tempus Hub、Lens、Next等临床与研究产品，并列示多款FDA许可ECG-AI产品。'),src('https://investors.tempus.com/news-events/news-releases','Tempus AI News Releases','发行人2026年公告披露ECG-MR获得FDA 510(k)许可，属于其第四款FDA许可ECG-AI产品。')],'official_review','high','AI诊断/临床工具直接证据明确；不能仅据此推断各应用的收入或临床效果。'),
 rec('HIMS','Hims & Hers Health','数字医疗与AI辅助照护服务','health',['health','applications'],3,['公司发布将AI嵌入患者照护流程的Hers应用，首批面向减重会员提供个性化支持、治疗进展跟踪，并在需要临床判断时接入医生与照护团队。'],[src('https://news.hims.com/newsroom/hims-hers-doctor-led-ai-native-care-experience','Hims & Hers Introduces Doctor-Led AI-Native Care Experience','公司公告称新Hers应用将AI融入会员照护，依据个人治疗计划提供支持，医生保留临床判断；首期面向减重会员推出。'),src('https://news.hims.com/newsroom/building-better-health-ai-as-the-operating-system-for-care','Building Better Health: AI as the Operating System for Care','公司描述将AI用于接诊、分流、临床文档、随访与治疗依从等照护环节。')],'official_review','high','产品范围和首期会员群体明确；不代表AI独立营收或已经证明的临床结局。'),
 rec('OSCR','Oscar Health, Inc.','健康保险与会员AI服务','health',['health','applications'],3,['Oscar宣布向会员提供由OpenAI支持的Oswell健康AI代理，读取会员计划文件和医疗记录，回答用药/检验结果等问题并支持医疗导航。'],[src('https://ir.oscarhealth.com/news-events/press-releases/detail/108/oscar-unveils-new-choices-and-ai-tools-shaping-the-future-of-individual-healthcare-for-more-americans-and-businesses','Oscar Unveils New Choices and AI Tools','发行人明确宣布推出面向Oscar会员的Oswell AI健康代理，说明其整合病历、会员交互和保险计划文件的具体服务场景。')],'official_review','high','发行人披露产品发布；需区分健康保险核心承保业务和AI会员服务贡献。'),
 rec('DNA','Ginkgo Bioworks Holdings','细胞编程与合成生物平台','health',['health','data','compute'],2,['公司投资者资料将平台能力拆分为自动化实验室、专有生物数据、云计算及AI模型，并称AI模型套件已集成至工作流，为客户细胞编程/生物工程提供数据和实验支持。'],[src('https://investors.ginkgobioworks.com/files/doc_presentations/2024/01/JPM-2024-Ginkgo-Bioworks-Final-3.pdf','Ginkgo Bioworks JPM 2024 Presentation','发行人展示其技术栈中的“Compute + AI Models”，包括任务模型、foundation models、专有数据集及集成到工作流的AI模型套件。'),src('https://investors.ginkgobioworks.com/why-invest/default.aspx','Why Invest in Ginkgo Bioworks','公司称其向客户提供跨生物体细胞编程平台，服务多个研发市场。')],'official_review','medium','证明平台包含AI模型与自动化实验基础设施，但未将具体客户AI模型项目或收入占比量化。'),
 rec('ADPT','Adaptive Biotechnologies','免疫测序与AI免疫医学平台','health',['health','data'],3,['Adaptive描述其免疫医学平台为AI-enabled，基于大规模免疫受体数据和数百个AI模型注释免疫谱；发行人披露利用计算建模与机器学习开发临床诊断和药物发现。'],[src('https://www.adaptivebiotech.com/our-platform/','Adaptive Immune Medicine Platform','公司披露AI-enabled免疫医学平台、TCR数据集和260余个免疫谱注释模型，并说明以机器学习映射受体序列和抗原。'),src('https://investors.adaptivebiotech.com/news-releases/news-release-details/adaptive-biotechnologies-announces-plan-separate-its-mrd-and','Adaptive Announces Planned Separation of MRD and Immune Medicine','2026年发行人公告明确Immune Medicine业务使用专有免疫数据和AI驱动发现平台，并推进MRD与免疫医学业务分拆评估。')],'official_review','high','平台AI证据明确；公司同时经营MRD检测和免疫药物发现业务，需关注拟议分拆对暴露的影响。'),
 rec('INSP','Inspire Medical Systems','睡眠呼吸暂停植入式神经刺激器','health',['health'],0,['核查发行人官网治疗及产品介绍，确认其主营植入式上气道刺激治疗阻塞性睡眠呼吸暂停；所查材料未建立AI诊断、AI产品或AI专属供给路径。'],[src('https://www.inspiresleep.com/en-us/about-inspire/','About Inspire','公司介绍植入式神经刺激治疗和商业产品，所查资料未提及人工智能产品或AI供给。')],'official_review','low','负面结论仅限于所查公司业务页面；医疗设备和软件本身不自动构成AI关联。'),
 rec('RTX','RTX Corporation','航空航天与国防AI系统','applications',['applications','edge'],3,['RTX公开AI/自主防务具体产品与合作，包括Raytheon RAIVEN AI光电传感系统、AI/ML辅助超视距雷达，以及将Shield AI自主软件集成到选定RTX防务产品。'],[src('https://www.rtx.com/raytheon/what-we-do/air/raiven','RAIVEN AI-Enabled Electro-Optical and Infrared Sensing','RTX称RAIVEN产品家族使用AI识别目标并提升感知，适配空、地、海等平台。'),src('https://www.rtx.com/news/news-center/2025/07/01/rtx-and-shield-ai-partner-to-develop-new-defense-capabilities','RTX and Shield AI Partner to Develop New Defense Capabilities','公告称RTX将把Shield AI Hivemind和ViDAR集成到选定RTX产品，推进自主任务能力及AI目标感知。')],'official_review','high','AI产品和集成路径明确；RTX整体业务高度多元，AI占比不可由产品页面推断。'),
 rec('TER','Teradyne, Inc.','半导体测试与工业机器人','compute',['compute','edge','applications'],3,['Teradyne面向AI/云基础设施推出专用Titan HP系统级测试平台，并在机器人产品组合推出AI托盘识别；其最新年报亦指出AI应用拉动计算芯片测试收入。'],[src('https://investors.teradyne.com/news-events/press-releases/detail/424/teradyne-unveils-titan-hp','Teradyne Unveils Titan HP','公司宣布专为AI及云基础设施设备设计的系统级测试平台。'),src('https://investors.teradyne.com/news-events/press-releases/detail/32/teradyne-robotics-to-bring-the-power-of-ai-to-robotics-with-nvidia','Teradyne Robotics to Bring AI to Robotics with NVIDIA','公司披露MiR1200机器人使用AI托盘检测，及Universal Robots AI自主检查示范。'),src('https://investors.teradyne.com/sec-filings/all-sec-filings/content/0001193125-26-059002/ter-20251231.htm','Teradyne FY2025 Form 10-K','年报称半导体测试业务2025年由AI应用推动增长。')],'official_review','high','AI芯片测试需求与AI机器人产品同时存在；不可将AI驱动的半导体周期增长等同全公司纯AI收入。'),
]


records += [
 rec('LMT','Lockheed Martin Corporation','航空航天国防与AI软件平台','applications',['applications','edge','data'],3,['Lockheed Martin公开提供STAR.OS AI集成平台，用于连接政府/国防项目中的AI应用，且Astris AI对外提供安全MLOps和生成式AI平台；其AI能力已用于客户任务系统集成。'],[src('https://www.lockheedmartin.com/en-us/capabilities/artificial-intelligence-machine-learning/star-os-ai-integration-framework.html','STAR.OS AI Integration Framework','公司称STAR.OS含多个AI集成产品线，已用作政府/国防AI应用与项目系统之间的集成层，并有SAR自动目标识别、导弹预警与任务自主集成案例。'),src('https://www.lockheedmartin.com/en-us/capabilities/artificial-intelligence-machine-learning.html','Artificial Intelligence and Machine Learning','Lockheed披露Astris AI向外部高保障行业提供MLOps和生成式AI平台。')],'official_review','high','有明确AI软件/平台和国防集成路径，但具体收入及外部软件独立销售规模未披露。'),
 rec('NOC','Northrop Grumman Corporation','国防航天与AI任务系统','applications',['applications','edge','connect'],3,['Northrop产品ABMC2被描述为AI-enabled、TRL 9任务指挥控制平台，可融合AI传感器数据、自动分配传感任务并支持目标分类；其Talon IQ推进自主飞行部署。'],[src('https://www.northropgrumman.com/what-we-do/mission-solutions/abmc2','Advanced Battle Management Command & Control','公司介绍ABMC2为AI使能的成熟多域指挥控制平台，列出AI目标分类、自动化传感器调度和AI辅助战场管理功能。'),src('https://www.northropgrumman.com/what-we-do/aircraft/talon-iq','Talon IQ Autonomous Testbed','发行人披露Talon IQ利用任务自主软件及合作伙伴AI能力，快速整合和验证自主航空任务软件。')],'official_review','high','AI产品面向国防任务系统，业务受政府采购与项目周期影响。'),
 rec('GD','General Dynamics Corporation','国防任务系统与政府AI服务','applications',['applications','cloud','data'],2,['General Dynamics旗下GDIT与Google Public Sector合作，为国防/情报机构提供安全AI、云和边缘任务解决方案，并将数字加速器部署至云平台。'],[src('https://www.gd.com/Articles/2025/11/gdit-expands-collaboration-with-google-public-sector-to-drive-mission-ai-solutions','GDIT Expands Collaboration with Google Public Sector to Drive Mission AI Solutions','发行人称GDIT将整合Google Cloud AI、云和网络安全能力，面向国防、情报机构及政府数字化任务交付AI解决方案。'),src('https://www.gd.com/our-businesses/technologies','General Dynamics Technologies','公司说明技术部门面向政府/军方提供包括AI在内的专业技术、任务系统及ISR能力。')],'official_review','medium','AI服务是General Dynamics Technologies业务的一部分，不能外推至全公司造船和航空业务。'),
 rec('BA','The Boeing Company','航空航天与无人自主系统','edge',['edge','systems'],2,['Boeing的自主/无人系统产品组合包括MQ-25、MQ-28等无人平台；官方说明使用AI、通信和可扩展任务架构支持人机协同，MQ-25可自动滑行、起飞、飞行和着陆。'],[src('https://www.boeing.com/content/theboeingcompany/us/en/defense/autonomous-and-unmanned-systems.html','Boeing Autonomous and Unmanned Systems','Boeing将AI技术纳入无人系统产品组合，并列出MQ-25、MQ-28等自主系统及其任务协同方式。'),src('https://www.boeing.com/defense/mq25/','MQ-25 Stingray','公司说明MQ-25是舰载无人机，具备自主滑行、起飞、飞行、着陆及有人/无人协同能力。')],'official_review','medium','自主功能与AI明示于组合层面，单一产品具体AI功能、商业进度和收入贡献未拆分。'),
 rec('HII','Huntington Ingalls Industries','海军无人系统与国防AI平台','applications',['applications','edge'],3,['HII展示LeviathanAI企业级agentic AI平台，以及AI/ML情报和决策支持产品；公司还披露其Odyssey自治控制软件驱动的ROMULUS无人艇为AI-enabled，并已进行多域协同演示。'],[src('https://www.hii.com/capabilities/artificial-intelligence','HII Artificial Intelligence','HII列出LeviathanAI代理式AI平台，以及机器学习、深度学习、生成式AI、智能自主等业务产品。'),src('https://www.hii.com/news/hii-odyssey-advanced-autonomy-connects-remus-and-romulus-enabling-integrated-multi-domain-unmanned-operations','HII Odyssey Advanced Autonomy Connects REMUS and ROMULUS','发行人称ROMULUS AI-enabled无人艇由Odyssey自主控制系统驱动，并演示水面/水下系统协同。')],'official_review','high','平台及AI无人系统证据明确；全公司业务还包含造船和其他国防服务。'),
 rec('LHX','L3Harris Technologies','国防任务软件与无人自主系统','edge',['edge','applications','data'],3,['公司发布Actonyx AI全栈视觉智能平台，提供AI数据整理/标注/训练/部署；ASView海事自主控制软件使用AI/机器学习融合感知信息并执行任务自主。'],[src('https://www.l3harris.com/all-capabilities/actonyx-ai','Actonyx AI','L3Harris称Actonyx是可在云端、本地或隔离环境部署的AI平台，支持标注、训练、评估、部署和目标识别。'),src('https://www.l3harris.com/all-capabilities/autonomous-systems','Autonomous Systems','公司披露ASView使用AI和机器学习提供任务与态势感知自主能力；系统部署在无人水面舰等平台。')],'official_review','high','产品范围明确但公司主要收入仍是多元国防系统与服务。'),
 rec('WAB','Wabtec Corporation','铁路智能检测与运输自动化','edge',['edge','applications'],3,['Wabtec提供KinetiX铁路场站检测系统，采用AI视频/深度学习OCR与边缘计算识别、跟踪货车并辅助按实时运营状态调度。'],[src('https://www.wabteccorp.com/kinetix-inspection-technologies-Yard-System?inline=','KinetiX Inspection Technologies for Yards','公司产品说明称系统使用AI视频识别并跟踪铁路车辆；技术栈包含边缘计算、深度学习OCR和AI模型算法。'),src('https://www.wabteccorp.com/digital-intelligence','Wabtec Digital Intelligence','公司列出铁路数字化、监测、远程运行和调度优化产品线。')],'official_review','high','AI视觉产品明确；公司主要业务仍包括机车、零部件和铁路系统，不等于全业务AI暴露。'),
 rec('GEV','GE Vernova Inc.','发电、电网设备与数据中心能源方案','power',['power','energy'],2,['GE Vernova向数据中心提供AI负载适配的发电、电气化、UPS、储能和开关设备；与NVIDIA共同开发800V直流AI工厂参考架构，另披露为AI数据中心运营项目供电。'],[src('https://www.gevernova.com/electrification/industries/data-centers','GE Vernova Data Center Electrification Solutions','公司列出支持AI负载的电网到机架供电系统，含AI负载UPS、电气化设备，并披露与NVIDIA合作的800V直流AI工厂参考架构。'),src('https://www.gevernova.com/gas-power/industries/data-centers','GE Vernova Gas Power for Data Centers','公司提供面向生成式AI数据中心的现场发电、备用发电和混合微电网方案。')],'official_review','high','产品与方案直接适配AI数据中心供电；应进一步区分项目在手订单与全公司发电、电网业务。'),
 rec('PWR','Quanta Services, Inc.','电网工程与AI数据中心基础设施','power',['power','energy'],2,['Quanta年报具体说明其为AI训练和推理数据中心提供低压电气、模块化、变电站、输电互联及供电发电设施；技术与负载中心业务因大型数据中心建设扩大。'],[src('https://investors.quantaservices.com/sec-filings/all-sec-filings/content/0001050915-26-000006/pwr-20251231.htm','Quanta Services 2025 Form 10-K','年报把AI训练/推理数据中心投资与公司方案需求直接关联，并列出数据中心内部低压电力系统、变电站/输电互联及发电基础设施等服务。'),src('https://investors.quantaservices.com/_assets/_e85e2a5e6fe60c69e848b2fc49d6dcf2/quantaservices/db/894/10425/pdf/PWR%2B-%2B12.31.2025%2BER%2BOperational%2Band%2BFinancial%2BSummary.pdf','Quanta 2025 Operational and Financial Summary','公司介绍大型负载中心/数据中心建设项目扩展其供电与基础设施服务机会。')],'official_review','high','具体链路为工程承包和大型负载电力基础设施，不表示Quanta销售AI软件或专有计算产品。'),
 rec('ETN','Eaton Corporation plc','电力管理与AI数据中心基础设施','power',['power','energy'],2,['Eaton提供明确面向AI数据中心的电网到芯片电力设施组合，包括UPS、储能、微电网、中低压开关设备、模块化系统及AI工厂参考架构。'],[src('https://www.eaton.com/us/en-us/markets/data-centers/data-center-infrastructure-overview.html','Eaton Data Center Infrastructure for the AI Era','Eaton产品页将其供电、储能、UPS、微电网和开关设备明确面向AI数据中心部署及动态负载。'),src('https://www.eaton.com/us/en-us/markets/data-centers/impact-of-ai-data-center-infrastructure/beam-rubin-dsx.html','Eaton Beam Rubin DSX AI Factory Platform','公司发布基于NVIDIA参考架构的AI工厂电力、冷却和控制一体化平台。')],'official_review','high','基础设施产品与平台针对AI数据中心，但对Eaton整体营收及利润贡献未拆分。'),
]

OUT.write_text(json.dumps({'agent':'codex / gpt-6-luna','records':records},ensure_ascii=False,indent=2)+'\n')
print('wrote',len(records),'records')
