class Chart{
constructor(card,r){this.card=card;this.r=r;this.map=new Map(r.bars.map(b=>[b[0],b]));this.canvas=card.querySelector('.candle');this.mini=card.querySelector('.mini');this.start=card.querySelector('.start');this.end=card.querySelector('.end');this.slider=card.querySelector('.pan');this.offset=0;this.point=null;this.left=38;this.padRight=12;dateInputs(null,this.start,this.end);
card.querySelector('.apply').onclick=()=>this.setRange(this.start.value,this.end.value);card.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>this.setRange(clampDate(shift(this.end.value,-+b.dataset.days+1)),this.end.value));card.querySelector('.peak-jump').onclick=()=>this.jump(r.year_peak_date);card.querySelector('.low-jump').onclick=()=>this.jump(r.peak_after_low_date);card.querySelector('.left').onclick=()=>this.pan(-Math.max(1,Math.floor(this.capacity/2)));card.querySelector('.right').onclick=()=>this.pan(Math.max(1,Math.floor(this.capacity/2)));this.slider.oninput=()=>{this.offset=+this.slider.value;this.point=null;this.draw()};
this.canvas.addEventListener('click',e=>{this.point=this.indexAt(e.offsetX);this.draw()});this.canvas.addEventListener('mousemove',e=>{this.hover=this.indexAt(e.offsetX);this.draw()});this.canvas.addEventListener('mouseleave',()=>{this.hover=null;this.draw()});this.canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let p=this.point??this.offset;if(e.key==='Home')p=0;else if(e.key==='End')p=this.days.length-1;else p+=e.key==='ArrowRight'?1:-1;this.hover=null;this.point=Math.max(0,Math.min(this.days.length-1,p));if(this.point<this.offset)this.offset=this.point;if(this.point>=this.offset+this.capacity)this.offset=this.point-this.capacity+1;this.draw()}});
this.mini.addEventListener('click',e=>this.navigate(Math.round(e.offsetX/this.mini.clientWidth*(sessions.length-1))));this.mini.addEventListener('keydown',e=>{const moves={ArrowLeft:-1,ArrowRight:1,PageUp:-20,PageDown:20};if(e.key in moves||['Home','End'].includes(e.key)){e.preventDefault();let i=this.center??sessions.length-1;i=e.key==='Home'?0:e.key==='End'?sessions.length-1:i+moves[e.key];this.shiftWindow(e.key==='Home'?-Infinity:e.key==='End'?Infinity:moves[e.key])}});
this.setRange(globalStart,globalEnd);this.observer=new ResizeObserver(()=>{const old=this.capacity;this.dimensions();this.offset=Math.max(0,Math.min(this.offset,this.days.length-this.capacity));this.draw()});this.observer.observe(this.canvas)}
disconnect(){this.observer.disconnect()}
dimensions(){this.width=Math.max(120,this.canvas.clientWidth);this.capacity=Math.max(1,Math.floor((this.width-this.left-this.padRight)/6));this.step=Math.max(6,(this.width-this.left-this.padRight)/Math.max(1,Math.min(this.capacity,this.days?.length||1)))}
setRange(s,e){const err=this.card.querySelector('.local-error');if(!s||!e||s>e||s<minDate||e>maxDate){err.textContent='日期超出两年范围，或起点晚于终点。';return}err.textContent='';this.start.value=s;this.end.value=e;this.days=sessions.filter(d=>d>=s&&d<=e);this.dimensions();this.offset=Math.max(0,this.days.length-this.capacity);this.point=null;this.hover=null;this.center=sessions.indexOf(this.days[Math.floor(this.days.length/2)]||e);this.draw()}
jump(d){const span=Math.max(29,Math.round((new Date(this.end.value)-new Date(this.start.value))/86400000));let s=clampDate(shift(d,-Math.floor(span/2))),e=clampDate(shift(s,span));if(e===maxDate)s=clampDate(shift(e,-span));this.setRange(s,e);let i=this.days.indexOf(d);if(i>=0){this.offset=Math.max(0,Math.min(i-Math.floor(this.capacity/2),this.days.length-this.capacity));this.point=i;this.draw()}}
navigate(i){i=Math.max(0,Math.min(sessions.length-1,i));this.jump(sessions[i]);this.drawMini()}
shiftWindow(delta){if(!this.days.length)return;const count=this.days.length,first=sessions.indexOf(this.days[0]),limit=Math.max(0,sessions.length-count);let at=delta===-Infinity?0:delta===Infinity?limit:Math.max(0,Math.min(limit,first+delta));this.setRange(sessions[at],sessions[at+count-1])}
pan(n){this.offset=Math.max(0,Math.min(Math.max(0,this.days.length-this.capacity),this.offset+n));this.point=null;this.hover=null;this.draw()}
indexAt(x){return Math.max(this.offset,Math.min(this.days.length-1,this.offset+Math.floor((x-this.left)/this.step)))}
ctx(canvas,height){const dpr=devicePixelRatio||1,w=canvas.clientWidth;canvas.width=Math.round(w*dpr);canvas.height=Math.round(height*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,height);return c}
draw(){if(!this.canvas.clientWidth)return;this.dimensions();const c=this.ctx(this.canvas,236),w=this.width,top=16,bottom=165,volTop=185,volBottom=213,visible=this.days.slice(this.offset,this.offset+this.capacity),real=visible.map(d=>this.map.get(d)).filter(Boolean);c.font='10px system-ui';c.fillStyle='#666';if(!real.length){c.fillText('此区间无真实OHLC；缺失不补行情',this.left,90)}else{let hi=Math.max(...real.map(b=>b[2])),lo=Math.min(...real.map(b=>b[3]));if(this.r.reference_price<hi*1.05&&this.r.reference_price>lo*.95){hi=Math.max(hi,this.r.reference_price);lo=Math.min(lo,this.r.reference_price)}const pad=Math.max((hi-lo)*.08,hi*.005);hi+=pad;lo-=pad;const y=v=>bottom-(v-lo)/(hi-lo)*(bottom-top),maxVol=Math.max(...real.map(b=>b[5]),1);c.lineWidth=1;for(let j=0;j<4;j++){const v=lo+(hi-lo)*j/3,py=y(v);c.strokeStyle='#e2e2e2';c.beginPath();c.moveTo(this.left,py);c.lineTo(w-this.padRight,py);c.stroke();c.fillStyle='#666';c.fillText(fmt(v,1),1,py+3)}
const levels=[[this.r.reference_price,'参考'],[this.r.year_peak,'年高'],[this.r.peak_after_low,'峰后低']];for(const [v,label] of levels){if(v>=lo&&v<=hi){c.setLineDash([3,3]);c.strokeStyle='#888';c.beginPath();c.moveTo(this.left,y(v));c.lineTo(w-this.padRight,y(v));c.stroke();c.setLineDash([]);c.fillStyle='#555';c.fillText(label+' '+fmt(v),Math.max(this.left,w-104),y(v)-4)}}
visible.forEach((d,j)=>{const x=this.left+(j+.5)*this.step,b=this.map.get(d);if(!b){c.fillStyle='#ddd';c.fillRect(x-1,top,2,bottom-top);c.fillStyle='#666';c.fillText('缺',x-4,178);return}if(j&&Math.round((new Date(d)-new Date(visible[j-1]))/86400000)>1){c.strokeStyle='#ddd';c.lineWidth=1.5;c.beginPath();c.moveTo(x-this.step/2,top);c.lineTo(x-this.step/2,volBottom);c.stroke();c.lineWidth=1}c.strokeStyle='#333';c.beginPath();c.moveTo(x,y(b[2]));c.lineTo(x,y(b[3]));c.stroke();const bw=Math.max(2,Math.min(9,this.step*.65)),oy=y(b[1]),cy=y(b[4]),body=Math.max(1,Math.abs(oy-cy));c.fillStyle=b[4]>=b[1]?'#fff':'#555';c.fillRect(x-bw/2,Math.min(oy,cy),bw,body);c.strokeRect(x-bw/2,Math.min(oy,cy),bw,body);c.fillStyle='#999';c.fillRect(x-bw/2,volBottom-b[5]/maxVol*(volBottom-volTop),bw,b[5]/maxVol*(volBottom-volTop));if(d===this.r.year_peak_date||d===this.r.peak_after_low_date){c.fillStyle='#222';c.fillText(d===this.r.year_peak_date?'高':'低',x-4,10)}});c.fillStyle='#666';c.fillText('成交量',1,197);const p=this.hover??this.point;if(p!=null&&p>=this.offset&&p<this.offset+visible.length){const x=this.left+(p-this.offset+.5)*this.step;c.strokeStyle='#111';c.beginPath();c.moveTo(x,top);c.lineTo(x,volBottom);c.stroke()}}
c.fillStyle='#666';if(visible.length){c.fillText(visible[0],this.left,230);const last=visible.at(-1);c.fillText(last,Math.max(this.left,w-76),230)}this.slider.max=Math.max(0,this.days.length-this.capacity);this.slider.value=this.offset;this.slider.disabled=this.days.length<=this.capacity;this.card.querySelector('.left').disabled=this.offset===0;this.card.querySelector('.right').disabled=this.offset>=this.days.length-this.capacity;const missing=this.days.filter(d=>!this.map.has(d)).length;this.card.querySelector('.range-note').textContent=`选中 ${this.start.value}–${this.end.value}：${this.days.length}交易日 / 真实${this.days.length-missing}根 / 缺失${missing}日。可见 ${visible.length}日，间距${fmt(this.step,1)}px；全部区间可平移。`;
const chosen=this.hover??this.point??this.offset+visible.length-1,d=this.days[chosen],b=this.map.get(d);this.card.querySelector('.chart-readout').textContent=b?`${d} ET  开 ${usd(b[1])}  高 ${usd(b[2])}  低 ${usd(b[3])}  收 ${usd(b[4])}  量 ${fmt(b[5],0)}`:d?`${d} ET · 缺失真实日K`:'没有可见交易日';this.drawMini()}
drawMini(){const c=this.ctx(this.mini,66),w=this.mini.clientWidth,bars=this.r.bars;if(!bars.length)return;const high=Math.max(...bars.map(b=>b[2])),low=Math.min(...bars.map(b=>b[3])),step=w/sessions.length,y=v=>48-(v-low)/Math.max(.001,high-low)*42;c.fillStyle='#f4f4f4';c.fillRect(0,0,w,66);sessions.forEach((d,i)=>{const b=this.map.get(d),x=(i+.5)*step;if(!b){c.fillStyle='#ddd';c.fillRect(x,3,Math.max(.5,step*.6),46);return}c.strokeStyle='#777';c.lineWidth=.65;c.beginPath();c.moveTo(x,y(b[2]));c.lineTo(x,y(b[3]));c.stroke();c.fillStyle=b[4]>=b[1]?'#aaa':'#555';c.fillRect(x-step*.35,Math.min(y(b[1]),y(b[4])),Math.max(.5,step*.7),Math.max(1,Math.abs(y(b[1])-y(b[4]))))});const si=sessions.findIndex(d=>d>=this.start.value),ei=sessions.findLastIndex(d=>d<=this.end.value);if(si>=0&&ei>=si){c.fillStyle='rgba(0,0,0,.08)';c.fillRect(si*step,1,(ei-si+1)*step,51);c.strokeStyle='#111';c.lineWidth=2;c.strokeRect(si*step+1,1,Math.max(1,(ei-si+1)*step-2),51)}c.font='9px system-ui';c.fillStyle='#666';c.fillText(minDate,4,63);c.fillText(maxDate,w-65,63);this.mini.setAttribute('aria-valuenow',String(Math.max(0,this.center??0)));this.mini.setAttribute('aria-valuetext',`${this.start.value}至${this.end.value}`)}
}
