const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {chromium}=require('/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=__dirname;
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8768/analysis/stock_behavior_description_v1/detail.html',{waitUntil:'load'});
 await page.waitForFunction(()=>window.audit);
 assert.equal(await page.locator('#stockSelect option').count(),55);assert.equal(await page.locator('#frequency .scoreline').count(),2);assert.equal(await page.locator('#windowFilter option[value="quietUp"]').count(),0);
 assert.equal(await page.locator('#granularity').inputValue(),'hour');
 assert.equal(await page.locator('[data-overview]').count(),42);
 let def=await page.evaluate(()=>audit.getDescription());assert.equal(def.metrics.moveCount,7);assert.equal(def.shares.repeated,1);assert(Math.abs(def.metrics.net-.56867329047)<1e-9);
 assert((await page.locator('#description').innerText()).includes('净上行+56.9%'));
 assert((await page.locator('#frequencyNote').innerText()).includes('22个完整窗口'));
 assert.equal(await page.evaluate(()=>audit.getVisible().at(-1)[6]),'2026-10-07');
 let description=await page.locator('#description').innerText(),range0=[await page.locator('#start').inputValue(),await page.locator('#end').inputValue()];
 await page.locator('[data-move="0"]').click();assert.equal(await page.locator('#granularity').inputValue(),'day');
 assert(await page.locator('[data-evidence-shade]').count()>0);
 assert.equal(await page.locator('#description').innerText(),description);
 assert.deepEqual([await page.locator('#start').inputValue(),await page.locator('#end').inputValue()],range0);
 await page.locator('#latest').click();await page.locator('#wholeDaily').click();
 await page.locator('#windowFilter').selectOption('neither');let n=await page.evaluate(()=>audit.getDescription().windows.filter(v=>!v.up&&!v.repeated).length);
 assert.equal(await page.locator('#windows [data-window]').count(),n);
 await page.locator('#windowFilter').selectOption('all');await page.locator('#windows [data-window]').first().click();assert(await page.locator('#evidenceInfo').innerText().then(v=>v.includes('20个交易日变化')));
 await page.locator('#granularity').selectOption('hour');await page.locator('#firstPan').click();let first=await page.evaluate(()=>audit.getVisible()[0][0]);await page.locator('#nextPan').click();assert(await page.evaluate(()=>audit.getVisible()[0][0])>first);
 let before=await page.evaluate(()=>audit.getVisible().map(b=>b[0]));await page.locator('#chart').hover();await page.mouse.wheel(0,300);assert.deepEqual(await page.evaluate(()=>audit.getVisible().map(b=>b[0])),before);
 await page.locator('[data-bar="0"]').click();assert((await page.locator('#barInfo').innerText()).includes('归属交易日'));
 assert(await page.evaluate(()=>{let v=document.querySelector('#priceSvg').getAttribute('viewBox').split(' ').map(Number);return (v[2]-74)/audit.getVisible().length>=5}));
 await page.locator('#latest').click();await page.locator('#mini').focus();let end=await page.locator('#end').inputValue();await page.keyboard.press('ArrowLeft');assert(await page.locator('#end').inputValue()<end);
 await page.locator('#end').fill('2026-07-31');await page.locator('[data-days="30"]').click();assert.equal(await page.locator('#start').inputValue(),'2026-07-02');
 await page.locator('#stockSelect').selectOption('US.CBRS');assert(await page.locator('#description').innerText().then(v=>v.includes('净')));
 await page.locator('#stockSelect').selectOption('US.SOXL');assert((await page.locator('#identity').innerText()).includes('ETF'));
 await page.locator('details').filter({hasText:'公司的基本面、细分头部证据'}).locator('summary').click();assert((await page.locator('#fundamental').innerText()).includes('不适用'));
 await page.locator('#stockSelect').selectOption('HK.03006');await page.locator('#latest').click();await page.locator('#granularity').selectOption('hour');assert((await page.locator('#chart').innerText()).includes('没有真实'));
 assert((await page.locator('#descriptionScope').innerText()).includes('2026-10-06'));
 await page.locator('#stockSelect').selectOption('US.MXL');await page.locator('#latest').click();
 await page.locator('details').filter({hasText:'这些百分数的数学含义与探索参数'}).locator('summary').click();await page.locator('#threshold').selectOption('0.03');await page.locator('#windowSize').selectOption('10');await page.locator('#applyParams').click();
 assert((await page.locator('#parameterStatus').innerText()).includes('探索'));assert.equal(await page.evaluate(()=>audit.getDescription().shares.n),32);
 await page.locator('#resetParams').click();assert.equal(await page.evaluate(()=>audit.getDescription().shares.n),22);
 await page.locator('#verdict').selectOption('partial');await page.locator('#reviewNote').fill('Browser test: descriptive disagreement fixture.');await page.locator('#saveReview').click();assert((await page.locator('#reviewStatus').innerText()).includes('已保存'));
 const downloadPromise=page.waitForEvent('download');await page.locator('#exportReview').click();const download=await downloadPromise;const saved=await download.path(),review=JSON.parse(fs.readFileSync(saved));assert.equal(review.reviews[0].verdict,'partial');assert.equal(review.reviews[0].settings.threshold,.05);
 await page.reload({waitUntil:'load'});await page.waitForFunction(()=>window.audit);assert.equal(await page.locator('#verdict').inputValue(),'partial');
 await page.locator('#start').fill('2026-10-07');await page.locator('#end').fill('2026-10-07');await page.locator('#applyDates').click();assert((await page.locator('#description').innerText()).includes('一个真实收盘'));assert.equal(await page.evaluate(()=>audit.getDescription().shares),null);
 await page.locator('#latest').click();await page.evaluate(()=>{localStorage.removeItem('stock_historical_semantic_reviews_v1')});await page.reload({waitUntil:'load'});await page.waitForFunction(()=>window.audit);
 assert.equal(await page.locator('#verdict').inputValue(),'pending');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(out,'review-desktop.png')});
 await page.setViewportSize({width:390,height:844});await page.locator('#latest').click();await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:path.join(out,'review-mobile.png')});
 await page.locator('[data-days="180"]').click();assert(await page.evaluate(()=>document.querySelector('#overview').scrollWidth>document.querySelector('#overview').clientWidth));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.locator('details').filter({hasText:'比较全部特别关注：'}).locator('summary').click();await page.locator('#scope').selectOption('etf');assert.equal(await page.locator('#stocks [data-stock]').count(),17);
 await page.locator('#scope').selectOption('stock');assert.equal(await page.locator('#stocks [data-stock]').count(),38);await page.locator('#search').fill('MXL');assert.equal(await page.locator('#stocks [data-stock]').count(),1);
 await page.locator('details').filter({hasText:'数学定义、与原 G/V/M/J/S'}).locator('summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.equal(errors.length,0,errors.join(';'));
 const report={status:'passed',browser:'Playwright Chromium headless',desktop:[1440,1000],mobile:[390,844],errors,
  checks:['55 real members','whole interval OHLC overview','actual historical facts and window denominator','default ALL60m','move/window evidence without changing description scope','negative historical windows','explicit pan and >=5px','no wheel zoom','real OHLC bar info','2y mini keyboard','calendar dates','short history retained','ETF company fields separated','HK missing hourly/end retained','exploration parameters recompute history','keyed local review persistence and JSON export','one-bar abstention','wide/narrow no overflow and 180d contained overview','all-member filter/search','no simulated human acceptance'],
  html_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'detail.html'))).digest('hex')};
 fs.writeFileSync(path.join(out,'detail_browser_verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
